"""Org, membership, invite, and user-profile rows."""

from __future__ import annotations

from dataclasses import dataclass

@dataclass(frozen=True, slots=True)
class OrgRow:
    org_id: str
    name: str
    display_name: str
    description: str
    is_claimable: bool
    created_at: float
    icon_key: str = ""
    icon_github: str = ""

@dataclass(frozen=True, slots=True)
class MembershipRow:
    org_id: str
    user_id: str
    role: str
    created_at: float

@dataclass(frozen=True, slots=True)
class UserProfileRow:
    """GitHub profile snapshot written at Registry login (not a credential)."""

    user_id: str
    display_name: str
    avatar_url: str
    github_id: str
    description: str
    updated_at: float

@dataclass(frozen=True, slots=True)
class OrgInviteKeyRow:
    """Org invite key — at rest: token_hash + token_prefix only (no plaintext).

    Full secret is generated by the HTTP layer and returned **once** on create;
    redeem looks up by SHA-256 hash. Owner list/revoke never re-materialize the
    secret (industry default for invite/API keys).
    """

    key_id: str
    org_id: str
    token_hash: str
    token_prefix: str
    created_by: str
    max_uses: int | None
    use_count: int
    expires_at: float | None
    revoked_at: float | None
    created_at: float


def normalize_user_id(raw: str | None) -> str | None:
    if raw is None:
        return None
    u = str(raw).strip()
    if not u:
        return None
    return u.casefold()
