"""Shared Protocols for Registry metadata / token stores.

SQLite and Postgres adapters implement these contracts. Dialect differences
(placeholder style, connection lifecycle) stay inside each adapter.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Protocol, runtime_checkable

if TYPE_CHECKING:
    from services.registry.store import (
        AttemptResultRow,
        MembershipRow,
        OrgInviteKeyRow,
        OrgRow,
        ReleaseRow,
        ResultShareRow,
        SuiteResultRow,
        TokenInfo,
        UserProfileRow,
    )


@runtime_checkable
class TokenStoreProtocol(Protocol):
    def hash_token(self, raw: str) -> str: ...

    def add(
        self,
        raw_token: str,
        scopes: frozenset[str] | set[str],
        *,
        github_user: str | None = None,
    ) -> None: ...

    def auth_for(self, raw_token: str | None) -> TokenInfo: ...

    def scopes_for(self, raw_token: str | None) -> frozenset[str]: ...


@runtime_checkable
class MetadataStoreProtocol(Protocol):
    """Public surface shared by SQLite and Postgres metadata stores."""

    def insert(self, row: ReleaseRow) -> None: ...

    def get_by_version(self, database_id: str, version: str) -> ReleaseRow | None: ...

    def get_by_digest(self, database_id: str, package_digest: str) -> ReleaseRow | None: ...

    def list_releases(self, *args: Any, **kwargs: Any) -> list[ReleaseRow]: ...

    def list_versions(
        self, database_id: str, *, include_private: bool = False
    ) -> list[ReleaseRow]: ...

    def insert_attempt(self, row: AttemptResultRow) -> None: ...

    def get_attempt(self, run_id: str) -> AttemptResultRow | None: ...

    def list_attempts(self, *args: Any, **kwargs: Any) -> list[AttemptResultRow]: ...

    def insert_suite(self, row: SuiteResultRow) -> None: ...

    def get_suite(self, suite_run_id: str) -> SuiteResultRow | None: ...

    def list_suites(self, *args: Any, **kwargs: Any) -> list[SuiteResultRow]: ...

    def delete_attempt(self, run_id: str) -> AttemptResultRow: ...

    def delete_suite(self, suite_run_id: str) -> SuiteResultRow: ...

    def delete_release(self, database_id: str, version: str) -> ReleaseRow: ...

    def membership(self, org_id: str, user_id: str) -> MembershipRow | None: ...

    def get_org(self, org_id: str) -> OrgRow | None: ...

    def user_org_ids(self, user_id: str) -> set[str]: ...

    def result_shared_with_user(self, *args: Any, **kwargs: Any) -> bool: ...

    def attempts_for_ids(self, run_ids: list[str] | set[str]) -> list[AttemptResultRow]: ...

    def existing_attempt_ids(self, run_ids: list[str] | set[str]) -> set[str]: ...

    def set_attempt_visibility(self, run_id: str, visibility: str) -> AttemptResultRow: ...

    def set_suite_visibility(self, suite_run_id: str, visibility: str) -> SuiteResultRow: ...

    def list_attempts_for_suite(self, suite_run_id: str) -> list[AttemptResultRow]: ...

    def count_attempt_blob_refs(self, blob_digest: str) -> int: ...

    def count_suite_blob_refs(self, blob_digest: str) -> int: ...

    def count_package_blob_refs(self, blob_digest: str) -> int: ...

    def set_release_visibility(
        self, database_id: str, version: str, visibility: str
    ) -> ReleaseRow: ...

    def create_org(self, *args: Any, **kwargs: Any) -> OrgRow: ...

    def list_orgs_for_user(self, user_id: str) -> list[tuple[OrgRow, str]]: ...

    def claim_org(self, org_id: str, user_id: str) -> OrgRow: ...

    def add_member(self, org_id: str, user_id: str, *, role: str = "member") -> MembershipRow: ...

    def remove_member(self, org_id: str, user_id: str) -> None: ...

    def count_org_owners(self, org_id: str) -> int: ...

    def count_org_packages(self, org_id: str) -> int: ...

    def leave_org(self, org_id: str, user_id: str) -> None: ...

    def delete_org(self, org_id: str) -> None: ...

    def list_members(self, org_id: str) -> list[MembershipRow]: ...

    def create_invite_key(self, *args: Any, **kwargs: Any) -> Any: ...

    def list_invite_keys(self, org_id: str) -> list[OrgInviteKeyRow]: ...

    def get_invite_key(self, org_id: str, key_id: str) -> OrgInviteKeyRow | None: ...

    def revoke_invite_key(self, org_id: str, key_id: str) -> OrgInviteKeyRow: ...

    def redeem_invite_key(
        self, *, token_hash: str, user_id: str
    ) -> tuple[OrgRow, MembershipRow]: ...

    def add_result_share(self, *args: Any, **kwargs: Any) -> ResultShareRow: ...

    def remove_result_share(self, *args: Any, **kwargs: Any) -> None: ...

    def list_result_shares(self, *, result_kind: str, result_id: str) -> list[ResultShareRow]: ...

    def upsert_user_profile(self, *args: Any, **kwargs: Any) -> UserProfileRow: ...

    def get_user_profile(self, user_id: str) -> UserProfileRow | None: ...

    def get_user_profiles(self, user_ids: list[str] | set[str]) -> dict[str, UserProfileRow]: ...
