"""Registry metadata, tokens, results, and blob storage.

Unit tests: SQLite + Memory blob.
Compose / production: Postgres + S3-compatible (RustFS).

Raw API tokens are never persisted — only sha256 digests.
Visibility is only ``public`` | ``private``.
Packages require ``org_id`` on new publishes; results carry ``uploaded_by``
and optional share targets (org / user). Private read is ownership/membership
based (admin bypass); scopes alone no longer grant global private sight.
"""

from __future__ import annotations

import hashlib
import json
import sqlite3
import threading
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from services.registry import queries as Q
from services.registry.protocols import MetadataStoreProtocol, TokenStoreProtocol

# ---------------------------------------------------------------------------
# Rows
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class ReleaseRow:
    database_id: str
    version: str
    visibility: str
    package_digest: str
    blob_digest: str
    size: int
    media_type: str
    created_at: float
    org_id: str | None = None


@dataclass(frozen=True, slots=True)
class AttemptResultRow:
    """Sealed Attempt evidence bundle metadata (not a Database package)."""

    run_id: str
    database_id: str
    task_id: str
    lock_digest: str
    status: str
    visibility: str
    blob_digest: str
    size: int
    created_at: float
    uploaded_by: str = ""
    # Optional link to parent suite/job (#43); empty on standalone uploads.
    suite_run_id: str = ""


@dataclass(frozen=True, slots=True)
class SuiteResultRow:
    """Suite/job result row: aggregates + per-task refs (not suite PASS).

    Observational leaderboard input for Hub SPA (#22 S5). PASS remains
    per-task evaluator only.
    """

    suite_run_id: str
    database_id: str
    database_version: str
    visibility: str
    pass_rate: float
    mean_score: float
    metrics_json: str
    tasks_json: str
    agent_label: str
    model_label: str
    blob_digest: str
    size: int
    exit_code: int
    created_at: float
    # #42 config comparability (optional; empty/default on legacy rows)
    config_json: str = "{}"
    uploaded_by: str = ""
    complete: bool = False
    bound_kind: str = "unknown"
    task_set_digest: str = ""


@dataclass(frozen=True, slots=True)
class DraftRow:
    """One current draft slot per dataset (not a release)."""

    database_id: str
    org_id: str
    visibility: str
    package_digest: str
    blob_digest: str
    size: int
    media_type: str
    package_kind: str
    uploaded_by: str
    updated_at: float

    def as_release(self) -> ReleaseRow:
        return ReleaseRow(
            database_id=self.database_id,
            version="draft",
            visibility=self.visibility,
            package_digest=self.package_digest,
            blob_digest=self.blob_digest,
            size=self.size,
            media_type=self.media_type,
            created_at=self.updated_at,
            org_id=self.org_id,
        )


@dataclass(frozen=True, slots=True)
class DatasetAclRow:
    database_id: str
    user_id: str
    role: str
    created_at: float


@dataclass(frozen=True, slots=True)
class OrgRow:
    org_id: str
    name: str
    display_name: str
    is_claimable: bool
    created_at: float


@dataclass(frozen=True, slots=True)
class MembershipRow:
    org_id: str
    user_id: str
    role: str
    created_at: float


@dataclass(frozen=True, slots=True)
class UserProfileRow:
    """GitHub profile snapshot written at Registry login (not a credential)."""

    user_id: str
    display_name: str
    avatar_url: str
    github_id: str
    updated_at: float


@dataclass(frozen=True, slots=True)
class TokenInfo:
    """Resolved bearer token: scopes + optional user identity (github login)."""

    scopes: frozenset[str]
    user_id: str | None = None


@dataclass(frozen=True, slots=True)
class ResultShareRow:
    result_kind: str  # attempt | suite
    result_id: str
    target_type: str  # org | user
    target_id: str
    created_at: float


@dataclass(frozen=True, slots=True)
class OrgInviteKeyRow:
    """Org invite key — at rest: token_hash + token_prefix only (no plaintext).

    Full secret is generated by the HTTP layer and returned **once** on create;
    redeem looks up by SHA-256 hash. Owner list/revoke never re-materialize the
    secret (industry default for invite/API keys).
    """

    key_id: str
    org_id: str
    token_hash: str
    token_prefix: str
    created_by: str
    max_uses: int | None
    use_count: int
    expires_at: float | None
    revoked_at: float | None
    created_at: float


# ---------------------------------------------------------------------------
# Blob
# ---------------------------------------------------------------------------


class MemoryBlobStore:
    """Unit-test only blob backend."""

    def __init__(self) -> None:
        self._data: dict[str, bytes] = {}
        self._lock = threading.Lock()

    def _key(self, blob_digest: str, prefix: str) -> str:
        return f"{prefix}/{blob_digest}"

    def put_if_absent(self, blob_digest: str, data: bytes, *, prefix: str = "packages") -> None:
        with self._lock:
            self._data.setdefault(self._key(blob_digest, prefix), data)

    def get(self, blob_digest: str, *, prefix: str = "packages") -> bytes | None:
        with self._lock:
            return self._data.get(self._key(blob_digest, prefix))

    def delete(self, blob_digest: str, *, prefix: str = "packages") -> bool:
        """Remove blob if present. Returns True when a key was deleted."""
        with self._lock:
            return self._data.pop(self._key(blob_digest, prefix), None) is not None


class FilesystemBlobStore:
    """Dev fallback: local directory. Prefer S3 for compose e2e."""

    def __init__(self, root: Path) -> None:
        self.root = root
        self.root.mkdir(parents=True, exist_ok=True)

    def _path(self, blob_digest: str, prefix: str) -> Path:
        key = blob_digest.replace(":", "_")
        return self.root / prefix / key

    def put_if_absent(self, blob_digest: str, data: bytes, *, prefix: str = "packages") -> None:
        path = self._path(blob_digest, prefix)
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.exists():
            return
        tmp = path.with_suffix(".tmp")
        tmp.write_bytes(data)
        tmp.replace(path)

    def get(self, blob_digest: str, *, prefix: str = "packages") -> bytes | None:
        path = self._path(blob_digest, prefix)
        if not path.is_file():
            return None
        return path.read_bytes()

    def delete(self, blob_digest: str, *, prefix: str = "packages") -> bool:
        path = self._path(blob_digest, prefix)
        if not path.is_file():
            return False
        path.unlink()
        return True


class S3BlobStore:
    """S3-compatible blob store (RustFS / AWS). Credentials stay server-side only."""

    def __init__(
        self,
        *,
        endpoint: str,
        access_key: str,
        secret_key: str,
        bucket: str,
        region: str = "us-east-1",
    ) -> None:
        try:
            import boto3
            from botocore.client import Config
            from botocore.exceptions import ClientError
        except ImportError as exc:
            raise RuntimeError(
                "boto3 required for S3 blob backend; install with: uv sync --extra registry"
            ) from exc
        self._ClientError = ClientError
        self.bucket = bucket
        self._client = boto3.client(
            "s3",
            endpoint_url=endpoint.rstrip("/"),
            aws_access_key_id=access_key,
            aws_secret_access_key=secret_key,
            region_name=region,
            config=Config(signature_version="s3v4", s3={"addressing_style": "path"}),
        )
        self._ensure_bucket()

    def _ensure_bucket(self) -> None:
        import contextlib

        try:
            self._client.head_bucket(Bucket=self.bucket)
        except self._ClientError:
            with contextlib.suppress(self._ClientError):
                self._client.create_bucket(Bucket=self.bucket)

    def _object_key(self, blob_digest: str, prefix: str) -> str:
        return f"{prefix}/{blob_digest.replace(':', '_')}"

    def put_if_absent(self, blob_digest: str, data: bytes, *, prefix: str = "packages") -> None:
        key = self._object_key(blob_digest, prefix)
        try:
            self._client.head_object(Bucket=self.bucket, Key=key)
            return
        except self._ClientError:
            pass
        self._client.put_object(Bucket=self.bucket, Key=key, Body=data)

    def get(self, blob_digest: str, *, prefix: str = "packages") -> bytes | None:
        key = self._object_key(blob_digest, prefix)
        try:
            resp = self._client.get_object(Bucket=self.bucket, Key=key)
        except self._ClientError:
            return None
        return bytes(resp["Body"].read())

    def delete(self, blob_digest: str, *, prefix: str = "packages") -> bool:
        key = self._object_key(blob_digest, prefix)
        try:
            self._client.head_object(Bucket=self.bucket, Key=key)
        except self._ClientError:
            return False
        try:
            self._client.delete_object(Bucket=self.bucket, Key=key)
        except self._ClientError:
            return False
        return True


# ---------------------------------------------------------------------------
# Tokens
# ---------------------------------------------------------------------------


DEFAULT_LOGIN_SCOPES: frozenset[str] = frozenset(
    {
        "registry:publish",
        "read-private",
        "results:upload",
        "results:read",
    }
)

ADMIN_SCOPES: frozenset[str] = frozenset(
    {
        "admin",
        "registry:publish",
        "read-private",
        "results:upload",
        "results:read",
    }
)


def _normalize_user_id(raw: str | None) -> str | None:
    if raw is None:
        return None
    u = str(raw).strip()
    if not u:
        return None
    return u.casefold()


class TokenStore(TokenStoreProtocol):
    """In-memory tokens (tests). Prefer SqliteTokenStore / PostgresTokenStore."""

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._tokens: dict[str, TokenInfo] = {}

    def hash_token(self, raw: str) -> str:
        return hashlib.sha256(raw.encode("utf-8")).hexdigest()

    def add(
        self,
        raw_token: str,
        scopes: set[str] | frozenset[str],
        *,
        github_user: str | None = None,
    ) -> None:
        with self._lock:
            self._tokens[self.hash_token(raw_token)] = TokenInfo(
                scopes=frozenset(scopes),
                user_id=_normalize_user_id(github_user),
            )

    def auth_for(self, raw_token: str | None) -> TokenInfo:
        if not raw_token:
            return TokenInfo(scopes=frozenset())
        with self._lock:
            return self._tokens.get(self.hash_token(raw_token), TokenInfo(scopes=frozenset()))

    def scopes_for(self, raw_token: str | None) -> frozenset[str]:
        return self.auth_for(raw_token).scopes


class PersistentTokenStore(TokenStoreProtocol):
    """One token repository; SQLite / Postgres only differ in the adapter."""

    def __init__(self, *, adapter: Any) -> None:
        self._adapter = adapter
        self.db_path = getattr(adapter, "db_path", None)
        self._init()

    def _connect(self) -> Any:
        return self._adapter.connect()

    def _exec(self, conn: Any, sql: str, params: Any = ()) -> Any:
        return self._adapter.execute(conn, sql, params)

    def _init(self) -> None:
        with self._connect() as conn:
            for stmt in Q.SCHEMA_STATEMENTS:
                if "api_tokens" in stmt:
                    self._exec(conn, stmt)
            conn.commit()

    def hash_token(self, raw: str) -> str:
        return hashlib.sha256(raw.encode("utf-8")).hexdigest()

    def add(
        self,
        raw_token: str,
        scopes: set[str] | frozenset[str],
        *,
        github_user: str | None = None,
    ) -> None:
        scopes_json = json.dumps(sorted(scopes))
        with self._connect() as conn:
            self._exec(
                conn,
                Q.UPSERT_TOKEN,
                (self.hash_token(raw_token), scopes_json, github_user),
            )
            conn.commit()

    def auth_for(self, raw_token: str | None) -> TokenInfo:
        if not raw_token:
            return TokenInfo(scopes=frozenset())
        with self._connect() as conn:
            cur = self._exec(conn, Q.SELECT_TOKEN, (self.hash_token(raw_token),))
            row = cur.fetchone()
            if row is None or row.get("revoked_at") is not None:
                return TokenInfo(scopes=frozenset())
            scopes_raw = row["scopes"]
            try:
                data = scopes_raw if isinstance(scopes_raw, list) else json.loads(scopes_raw)
            except (TypeError, json.JSONDecodeError):
                return TokenInfo(scopes=frozenset())
            return TokenInfo(
                scopes=frozenset(str(s) for s in data),
                user_id=_normalize_user_id(row["github_user"]),
            )

    def scopes_for(self, raw_token: str | None) -> frozenset[str]:
        return self.auth_for(raw_token).scopes


class SqliteTokenStore(PersistentTokenStore):
    """Persistent tokens in the same SQLite file as metadata."""

    def __init__(self, db_path: Path) -> None:
        from services.registry.sql_adapter import SqliteAdapter

        PersistentTokenStore.__init__(self, adapter=SqliteAdapter(db_path))


class PostgresTokenStore(PersistentTokenStore):
    """Persistent tokens in Postgres."""

    def __init__(self, database_url: str) -> None:
        from services.registry.sql_adapter import PostgresAdapter

        PersistentTokenStore.__init__(self, adapter=PostgresAdapter(database_url))
        self.database_url = database_url


# ---------------------------------------------------------------------------
# Metadata (packages + attempt results + orgs + shares)
# ---------------------------------------------------------------------------


class MetadataStore(MetadataStoreProtocol):
    """One metadata repository; SQLite / Postgres only differ in the adapter."""

    def __init__(self, db_path: Path | None = None, *, adapter: Any | None = None) -> None:
        from services.registry.sql_adapter import SqliteAdapter

        if adapter is not None:
            self._adapter = adapter
        else:
            if db_path is None:
                raise TypeError("MetadataStore requires db_path or adapter")
            self._adapter = SqliteAdapter(db_path)
        self.db_path = getattr(self._adapter, "db_path", db_path)
        self._init()

    def _connect(self) -> Any:
        return self._adapter.connect()

    def _exec(self, conn: Any, sql: str, params: Any = ()) -> Any:
        return self._adapter.execute(conn, sql, params)

    def _init(self) -> None:
        with self._connect() as conn:
            for stmt in Q.SCHEMA_STATEMENTS:
                if "api_tokens" in stmt:
                    continue
                self._exec(conn, stmt)
            for table, column, decl in Q.SCHEMA_MIGRATIONS:
                self._adapter.add_column(conn, table, column, decl)
            conn.commit()

    def insert(self, row: ReleaseRow) -> None:
        with self._connect() as conn:
            try:
                self._exec(
                    conn,
                    Q.INSERT_RELEASE,
                    (
                        row.database_id,
                        row.version,
                        row.visibility,
                        row.package_digest,
                        row.blob_digest,
                        row.size,
                        row.media_type,
                        row.created_at,
                        row.org_id,
                    ),
                )
                conn.commit()
            except self._adapter.integrity_error as exc:
                raise ValueError("release already exists") from exc

    def get_by_version(self, database_id: str, version: str) -> ReleaseRow | None:
        with self._connect() as conn:
            cur = self._exec(conn, Q.SELECT_RELEASE_BY_VERSION, (database_id, version))
            r = cur.fetchone()
            return self._release_row(r) if r else None

    def get_by_digest(self, database_id: str, package_digest: str) -> ReleaseRow | None:
        with self._connect() as conn:
            cur = self._exec(conn, Q.SELECT_RELEASE_BY_DIGEST, (database_id, package_digest))
            r = cur.fetchone()
            return self._release_row(r) if r else None

    def list_releases(
        self,
        *,
        database_id_prefix: str | None = None,
        visibility: str | None = None,
        version: str | None = None,
        include_private: bool = False,
    ) -> list[ReleaseRow]:
        sql, params = Q.list_releases_query(
            database_id_prefix=database_id_prefix,
            visibility=visibility,
            version=version,
            include_private=include_private,
        )
        with self._connect() as conn:
            cur = self._exec(conn, sql, params)
            return [self._release_row(r) for r in cur.fetchall()]

    def list_versions(self, database_id: str, *, include_private: bool = False) -> list[ReleaseRow]:
        sql, params = Q.list_versions_query(database_id, include_private=include_private)
        with self._connect() as conn:
            cur = self._exec(conn, sql, params)
            return [self._release_row(r) for r in cur.fetchall()]

    def insert_attempt(self, row: AttemptResultRow) -> None:
        with self._connect() as conn:
            try:
                self._exec(
                    conn,
                    Q.INSERT_ATTEMPT,
                    (
                        row.run_id,
                        row.database_id,
                        row.task_id,
                        row.lock_digest,
                        row.status,
                        row.visibility,
                        row.blob_digest,
                        row.size,
                        row.created_at,
                        row.uploaded_by or "",
                        row.suite_run_id or "",
                    ),
                )
                conn.commit()
            except self._adapter.integrity_error as exc:
                raise ValueError("attempt result already exists") from exc

    def get_attempt(self, run_id: str) -> AttemptResultRow | None:
        with self._connect() as conn:
            cur = self._exec(conn, Q.SELECT_ATTEMPT, (run_id,))
            r = cur.fetchone()
            return self._attempt_row(r) if r else None

    def attempts_for_ids(self, run_ids: list[str] | set[str]) -> list[AttemptResultRow]:
        """Return attempt rows for the given run_ids (any visibility; caller filters)."""
        ids = sorted({str(r).strip() for r in run_ids if r and str(r).strip()})
        if not ids:
            return []
        with self._connect() as conn:
            cur = self._exec(
                conn,
                Q.select_attempts_in_query(len(ids)),
                ids,
            )
            return [self._attempt_row(r) for r in cur.fetchall()]

    def existing_attempt_ids(self, run_ids: list[str] | set[str]) -> set[str]:
        """Return the subset of *run_ids* that already have attempt rows (any visibility)."""
        return {row.run_id for row in self.attempts_for_ids(run_ids)}

    def list_attempts(
        self,
        *,
        database_id: str | None = None,
        include_private: bool = False,
    ) -> list[AttemptResultRow]:
        sql, params = Q.list_attempts_query(
            database_id=database_id, include_private=include_private
        )
        with self._connect() as conn:
            cur = self._exec(conn, sql, params)
            return [self._attempt_row(r) for r in cur.fetchall()]

    def insert_suite(self, row: SuiteResultRow) -> None:
        with self._connect() as conn:
            try:
                self._exec(
                    conn,
                    Q.INSERT_SUITE,
                    (
                        row.suite_run_id,
                        row.database_id,
                        row.database_version,
                        row.visibility,
                        row.pass_rate,
                        row.mean_score,
                        row.metrics_json,
                        row.tasks_json,
                        row.agent_label,
                        row.model_label,
                        row.blob_digest,
                        row.size,
                        row.exit_code,
                        row.created_at,
                        row.config_json or "{}",
                        row.uploaded_by or "",
                        1 if row.complete else 0,
                        row.bound_kind or "unknown",
                        row.task_set_digest or "",
                    ),
                )
                conn.commit()
            except self._adapter.integrity_error as exc:
                raise ValueError("suite result already exists") from exc

    def get_suite(self, suite_run_id: str) -> SuiteResultRow | None:
        with self._connect() as conn:
            cur = self._exec(conn, Q.SELECT_SUITE, (suite_run_id,))
            r = cur.fetchone()
            return self._suite_row(r) if r else None

    def list_suites(
        self,
        *,
        database_id: str | None = None,
        include_private: bool = False,
    ) -> list[SuiteResultRow]:
        sql, params = Q.list_suites_query(database_id=database_id, include_private=include_private)
        with self._connect() as conn:
            cur = self._exec(conn, sql, params)
            return [self._suite_row(r) for r in cur.fetchall()]

    def delete_attempt(self, run_id: str) -> AttemptResultRow:
        """Delete attempt row and its shares. Raises LookupError if missing."""
        row = self.get_attempt(run_id)
        if row is None:
            raise LookupError("attempt not found")
        with self._connect() as conn:
            self._exec(conn, Q.DELETE_ATTEMPT_SHARES, (run_id,))
            self._exec(conn, Q.DELETE_ATTEMPT, (run_id,))
            conn.commit()
        return row

    def set_attempt_visibility(self, run_id: str, visibility: str) -> AttemptResultRow:
        if visibility not in {"public", "private"}:
            raise ValueError("bad visibility")
        row = self.get_attempt(run_id)
        if row is None:
            raise LookupError("attempt not found")
        with self._connect() as conn:
            self._exec(
                conn,
                Q.UPDATE_ATTEMPT_VISIBILITY,
                (visibility, run_id),
            )
            conn.commit()
        updated = self.get_attempt(run_id)
        assert updated is not None
        return updated

    def delete_suite(self, suite_run_id: str) -> SuiteResultRow:
        """Delete suite row and its shares (does not cascade attempts)."""
        row = self.get_suite(suite_run_id)
        if row is None:
            raise LookupError("suite not found")
        with self._connect() as conn:
            self._exec(conn, Q.DELETE_SUITE_SHARES, (suite_run_id,))
            self._exec(conn, Q.DELETE_SUITE, (suite_run_id,))
            conn.commit()
        return row

    def set_suite_visibility(self, suite_run_id: str, visibility: str) -> SuiteResultRow:
        if visibility not in {"public", "private"}:
            raise ValueError("bad visibility")
        row = self.get_suite(suite_run_id)
        if row is None:
            raise LookupError("suite not found")
        with self._connect() as conn:
            self._exec(
                conn,
                Q.UPDATE_SUITE_VISIBILITY,
                (visibility, suite_run_id),
            )
            conn.commit()
        updated = self.get_suite(suite_run_id)
        assert updated is not None
        return updated

    def list_attempts_for_suite(self, suite_run_id: str) -> list[AttemptResultRow]:
        """Attempts whose suite_run_id column matches (any visibility)."""
        with self._connect() as conn:
            cur = self._exec(
                conn,
                Q.SELECT_ATTEMPTS_FOR_SUITE,
                (suite_run_id,),
            )
            return [self._attempt_row(r) for r in cur.fetchall()]

    def count_attempt_blob_refs(self, blob_digest: str) -> int:
        with self._connect() as conn:
            cur = self._exec(
                conn,
                Q.COUNT_ATTEMPT_BLOB_REFS,
                (blob_digest,),
            )
            return int(cur.fetchone()["n"])

    def count_suite_blob_refs(self, blob_digest: str) -> int:
        with self._connect() as conn:
            cur = self._exec(
                conn,
                Q.COUNT_SUITE_BLOB_REFS,
                (blob_digest,),
            )
            return int(cur.fetchone()["n"])

    def count_package_blob_refs(self, blob_digest: str) -> int:
        with self._connect() as conn:
            cur = self._exec(
                conn,
                Q.COUNT_PACKAGE_BLOB_REFS,
                (blob_digest,),
            )
            n = int(cur.fetchone()["n"])
            cur_d = self._exec(conn, Q.COUNT_DRAFT_BLOB_REFS, (blob_digest,))
            return n + int(cur_d.fetchone()["n"])

    def delete_release(self, database_id: str, version: str) -> ReleaseRow:
        row = self.get_by_version(database_id, version)
        if row is None:
            raise LookupError("release not found")
        with self._connect() as conn:
            self._exec(
                conn,
                Q.DELETE_RELEASE,
                (database_id, version),
            )
            conn.commit()
        return row

    def set_release_visibility(self, database_id: str, version: str, visibility: str) -> ReleaseRow:
        if visibility not in {"public", "private"}:
            raise ValueError("bad visibility")
        row = self.get_by_version(database_id, version)
        if row is None:
            raise LookupError("release not found")
        with self._connect() as conn:
            self._exec(
                conn,
                Q.UPDATE_RELEASE_VISIBILITY,
                (visibility, database_id, version),
            )
            conn.commit()
        updated = self.get_by_version(database_id, version)
        assert updated is not None
        return updated

    def upsert_draft(self, row: DraftRow) -> DraftRow:
        with self._connect() as conn:
            self._exec(
                conn,
                Q.UPSERT_DRAFT,
                (
                    row.database_id,
                    row.org_id,
                    row.visibility,
                    row.package_digest,
                    row.blob_digest,
                    row.size,
                    row.media_type,
                    row.package_kind,
                    row.uploaded_by,
                    row.updated_at,
                ),
            )
            conn.commit()
        stored = self.get_draft(row.database_id)
        assert stored is not None
        return stored

    def get_draft(self, database_id: str) -> DraftRow | None:
        with self._connect() as conn:
            cur = self._exec(conn, Q.SELECT_DRAFT, (database_id,))
            r = cur.fetchone()
            return self._draft_row(r) if r else None

    def get_draft_by_digest(self, database_id: str, package_digest: str) -> DraftRow | None:
        with self._connect() as conn:
            cur = self._exec(conn, Q.SELECT_DRAFT_BY_DIGEST, (database_id, package_digest))
            r = cur.fetchone()
            return self._draft_row(r) if r else None

    def list_drafts(self) -> list[DraftRow]:
        with self._connect() as conn:
            cur = self._exec(conn, Q.LIST_DRAFTS)
            return [self._draft_row(r) for r in cur.fetchall()]

    def delete_draft(self, database_id: str) -> DraftRow:
        row = self.get_draft(database_id)
        if row is None:
            raise LookupError("draft not found")
        with self._connect() as conn:
            self._exec(conn, Q.DELETE_DRAFT, (database_id,))
            conn.commit()
        return row

    def upsert_dataset_acl(
        self, database_id: str, user_id: str, *, role: str, created_at: float | None = None
    ) -> DatasetAclRow:
        ts = created_at if created_at is not None else now()
        with self._connect() as conn:
            self._exec(conn, Q.UPSERT_DATASET_ACL, (database_id, user_id, role, ts))
            conn.commit()
        row = self.dataset_acl(database_id, user_id)
        assert row is not None
        return row

    def dataset_acl(self, database_id: str, user_id: str) -> DatasetAclRow | None:
        with self._connect() as conn:
            cur = self._exec(conn, Q.SELECT_DATASET_ACL, (database_id, user_id))
            r = cur.fetchone()
            return self._dataset_acl_row(r) if r else None

    def list_dataset_acl(self, database_id: str) -> list[DatasetAclRow]:
        with self._connect() as conn:
            cur = self._exec(conn, Q.LIST_DATASET_ACL, (database_id,))
            return [self._dataset_acl_row(r) for r in cur.fetchall()]

    @staticmethod
    def _draft_row(r: sqlite3.Row) -> DraftRow:
        return DraftRow(
            database_id=str(r["database_id"]),
            org_id=str(r["org_id"] or ""),
            visibility=str(r["visibility"]),
            package_digest=str(r["package_digest"]),
            blob_digest=str(r["blob_digest"]),
            size=int(r["size"]),
            media_type=str(r["media_type"]),
            package_kind=str(r["package_kind"] or "database"),
            uploaded_by=str(r["uploaded_by"] or ""),
            updated_at=float(r["updated_at"]),
        )

    @staticmethod
    def _dataset_acl_row(r: sqlite3.Row) -> DatasetAclRow:
        return DatasetAclRow(
            database_id=str(r["database_id"]),
            user_id=str(r["user_id"]),
            role=str(r["role"]),
            created_at=float(r["created_at"]),
        )

    @staticmethod
    def _release_row(r: sqlite3.Row) -> ReleaseRow:
        keys = r.keys()
        org_id = r["org_id"] if "org_id" in keys else None
        return ReleaseRow(
            database_id=r["database_id"],
            version=r["version"],
            visibility=r["visibility"],
            package_digest=r["package_digest"],
            blob_digest=r["blob_digest"],
            size=int(r["size"]),
            media_type=r["media_type"],
            created_at=float(r["created_at"]),
            org_id=str(org_id) if org_id else None,
        )

    @staticmethod
    def _attempt_row(r: sqlite3.Row) -> AttemptResultRow:
        keys = r.keys()
        uploaded_by = str(r["uploaded_by"]) if "uploaded_by" in keys and r["uploaded_by"] else ""
        suite_run_id = (
            str(r["suite_run_id"]) if "suite_run_id" in keys and r["suite_run_id"] else ""
        )
        return AttemptResultRow(
            run_id=r["run_id"],
            database_id=r["database_id"],
            task_id=r["task_id"],
            lock_digest=r["lock_digest"],
            status=r["status"],
            visibility=r["visibility"],
            blob_digest=r["blob_digest"],
            size=int(r["size"]),
            created_at=float(r["created_at"]),
            uploaded_by=uploaded_by,
            suite_run_id=suite_run_id,
        )

    @staticmethod
    def _suite_row(r: sqlite3.Row) -> SuiteResultRow:
        keys = r.keys()
        config_json = str(r["config_json"]) if "config_json" in keys and r["config_json"] else "{}"
        uploaded_by = str(r["uploaded_by"]) if "uploaded_by" in keys and r["uploaded_by"] else ""
        complete = False
        if "complete" in keys and r["complete"] is not None:
            complete = bool(int(r["complete"]))
        bound_kind = (
            str(r["bound_kind"]) if "bound_kind" in keys and r["bound_kind"] else "unknown"
        )
        task_set_digest = (
            str(r["task_set_digest"])
            if "task_set_digest" in keys and r["task_set_digest"]
            else ""
        )
        return SuiteResultRow(
            suite_run_id=r["suite_run_id"],
            database_id=r["database_id"],
            database_version=r["database_version"],
            visibility=r["visibility"],
            pass_rate=float(r["pass_rate"]),
            mean_score=float(r["mean_score"]),
            metrics_json=str(r["metrics_json"]),
            tasks_json=str(r["tasks_json"]),
            agent_label=str(r["agent_label"] or ""),
            model_label=str(r["model_label"] or ""),
            blob_digest=r["blob_digest"],
            size=int(r["size"]),
            exit_code=int(r["exit_code"]),
            created_at=float(r["created_at"]),
            config_json=config_json,
            uploaded_by=uploaded_by,
            complete=complete,
            bound_kind=bound_kind,
            task_set_digest=task_set_digest,
        )

    # ---- organizations ---------------------------------------------------

    def create_org(
        self,
        *,
        name: str,
        owner_user_id: str,
        display_name: str = "",
        is_claimable: bool = False,
    ) -> OrgRow:
        org_id = name
        row = OrgRow(
            org_id=org_id,
            name=name,
            display_name=display_name or name,
            is_claimable=is_claimable,
            created_at=now(),
        )
        with self._connect() as conn:
            try:
                self._exec(
                    conn,
                    Q.INSERT_ORG,
                    (
                        row.org_id,
                        row.name,
                        row.display_name,
                        1 if row.is_claimable else 0,
                        row.created_at,
                    ),
                )
                self._exec(
                    conn,
                    Q.INSERT_ORG_OWNER_MEMBERSHIP,
                    (row.org_id, owner_user_id, row.created_at),
                )
                conn.commit()
            except self._adapter.integrity_error as exc:
                raise ValueError("org already exists") from exc
        return row

    def get_org(self, org_id: str) -> OrgRow | None:
        with self._connect() as conn:
            cur = self._exec(conn, Q.SELECT_ORG, (org_id,))
            r = cur.fetchone()
            return self._org_row(r) if r else None

    def list_orgs_for_user(self, user_id: str) -> list[tuple[OrgRow, str]]:
        with self._connect() as conn:
            cur = self._exec(conn, Q.SELECT_USER_ORGS, (user_id,))
            out: list[tuple[OrgRow, str]] = []
            for r in cur.fetchall():
                out.append((self._org_row(r), str(r["membership_role"])))
            return out

    def claim_org(self, org_id: str, user_id: str) -> OrgRow:
        with self._connect() as conn:
            cur = self._exec(conn, Q.SELECT_ORG, (org_id,))
            r = cur.fetchone()
            if r is None:
                raise LookupError("org not found")
            org = self._org_row(r)
            if not org.is_claimable:
                raise PermissionError("org not claimable")
            owners = self._exec(
                conn,
                Q.SELECT_ORG_HAS_OWNER,
                (org_id,),
            ).fetchone()
            if owners is not None:
                raise PermissionError("org already claimed")
            self._exec(
                conn,
                Q.INSERT_ORG_MEMBERSHIP_OWNER,
                (org_id, user_id, now()),
            )
            self._exec(
                conn,
                Q.UPDATE_ORG_CLAIMED,
                (org_id,),
            )
            conn.commit()
        got = self.get_org(org_id)
        assert got is not None
        return got

    def add_member(self, org_id: str, user_id: str, *, role: str = "member") -> MembershipRow:
        if role not in {"owner", "member"}:
            raise ValueError("invalid role")
        ts = now()
        with self._connect() as conn:
            if self.get_org(org_id) is None:
                raise LookupError("org not found")
            try:
                self._exec(
                    conn,
                    Q.INSERT_ORG_MEMBERSHIP,
                    (org_id, user_id, role, ts),
                )
                conn.commit()
            except self._adapter.integrity_error as exc:
                raise ValueError("membership exists") from exc
        return MembershipRow(org_id=org_id, user_id=user_id, role=role, created_at=ts)

    def remove_member(self, org_id: str, user_id: str) -> None:
        with self._connect() as conn:
            cur = self._exec(
                conn,
                Q.DELETE_ORG_MEMBERSHIP,
                (org_id, user_id),
            )
            if cur.rowcount == 0:
                raise LookupError("membership not found")
            conn.commit()

    def count_org_owners(self, org_id: str) -> int:
        with self._connect() as conn:
            cur = self._exec(
                conn,
                Q.COUNT_ORG_OWNERS,
                (org_id,),
            )
            r = cur.fetchone()
            return int(r["n"] if r is not None else 0)

    def count_org_packages(self, org_id: str) -> int:
        with self._connect() as conn:
            cur = self._exec(
                conn,
                Q.COUNT_ORG_PACKAGES,
                (org_id,),
            )
            r = cur.fetchone()
            return int(r["n"] if r is not None else 0)

    def leave_org(self, org_id: str, user_id: str) -> None:
        """Member (or non-sole owner) leaves the org."""
        uid = _normalize_user_id(user_id) or user_id
        mem = self.membership(org_id, uid)
        if mem is None:
            raise LookupError("membership not found")
        if mem.role == "owner" and self.count_org_owners(org_id) <= 1:
            raise PermissionError("sole owner cannot leave; dissolve the organization instead")
        self.remove_member(org_id, uid)

    def delete_org(self, org_id: str) -> None:
        """Dissolve org: memberships + invite keys + org row. Fail if packages remain."""
        if self.get_org(org_id) is None:
            raise LookupError("org not found")
        n_pkg = self.count_org_packages(org_id)
        if n_pkg > 0:
            raise ValueError(
                f"org still has {n_pkg} package release(s); unpublish or reassign first"
            )
        with self._connect() as conn:
            self._exec(conn, Q.DELETE_ORG_INVITE_KEYS, (org_id,))
            self._exec(conn, Q.DELETE_ORG_MEMBERSHIPS, (org_id,))
            self._exec(conn, Q.DELETE_ORG_RESULT_SHARES, (org_id,))
            cur = self._exec(conn, Q.DELETE_ORG, (org_id,))
            if cur.rowcount == 0:
                raise LookupError("org not found")
            conn.commit()

    def list_members(self, org_id: str) -> list[MembershipRow]:
        with self._connect() as conn:
            cur = self._exec(
                conn,
                Q.SELECT_ORG_MEMBERS,
                (org_id,),
            )
            return [
                MembershipRow(
                    org_id=str(r["org_id"]),
                    user_id=str(r["user_id"]),
                    role=str(r["role"]),
                    created_at=float(r["created_at"]),
                )
                for r in cur.fetchall()
            ]

    def membership(self, org_id: str, user_id: str) -> MembershipRow | None:
        with self._connect() as conn:
            cur = self._exec(conn, Q.SELECT_MEMBERSHIP, (org_id, user_id))
            r = cur.fetchone()
            if r is None:
                return None
            return MembershipRow(
                org_id=str(r["org_id"]),
                user_id=str(r["user_id"]),
                role=str(r["role"]),
                created_at=float(r["created_at"]),
            )

    def create_invite_key(
        self,
        *,
        org_id: str,
        created_by: str,
        token_hash: str,
        token_prefix: str,
        max_uses: int | None = None,
        expires_at: float | None = None,
        key_id: str | None = None,
    ) -> OrgInviteKeyRow:
        import secrets as _secrets

        if self.get_org(org_id) is None:
            raise LookupError("org not found")
        if max_uses is not None and max_uses < 1:
            raise ValueError("max_uses must be >= 1")
        if not token_hash or not token_prefix:
            raise ValueError("token_hash and token_prefix required")
        kid = key_id or _secrets.token_hex(8)
        row = OrgInviteKeyRow(
            key_id=kid,
            org_id=org_id,
            token_hash=token_hash,
            token_prefix=token_prefix,
            created_by=created_by or "",
            max_uses=max_uses,
            use_count=0,
            expires_at=expires_at,
            revoked_at=None,
            created_at=now(),
        )
        with self._connect() as conn:
            self._exec(
                conn,
                Q.INSERT_INVITE_KEY,
                (
                    row.key_id,
                    row.org_id,
                    row.token_hash,
                    row.token_prefix,
                    row.created_by,
                    row.max_uses,
                    row.use_count,
                    row.expires_at,
                    row.revoked_at,
                    row.created_at,
                ),
            )
            conn.commit()
        return row

    def list_invite_keys(self, org_id: str) -> list[OrgInviteKeyRow]:
        with self._connect() as conn:
            cur = self._exec(
                conn,
                Q.SELECT_INVITE_KEYS,
                (org_id,),
            )
            return [self._invite_key_row(r) for r in cur.fetchall()]

    def get_invite_key(self, org_id: str, key_id: str) -> OrgInviteKeyRow | None:
        with self._connect() as conn:
            cur = self._exec(
                conn,
                Q.SELECT_INVITE_KEY,
                (org_id, key_id),
            )
            r = cur.fetchone()
            return self._invite_key_row(r) if r else None

    def revoke_invite_key(self, org_id: str, key_id: str) -> OrgInviteKeyRow:
        ts = now()
        with self._connect() as conn:
            cur = self._exec(
                conn,
                Q.SELECT_INVITE_KEY,
                (org_id, key_id),
            )
            r = cur.fetchone()
            if r is None:
                raise LookupError("invite key not found")
            row = self._invite_key_row(r)
            if row.revoked_at is not None:
                return row
            self._exec(
                conn,
                Q.UPDATE_INVITE_REVOKED,
                (ts, key_id),
            )
            conn.commit()
        out = self.get_invite_key(org_id, key_id)
        assert out is not None
        return out

    def redeem_invite_key(self, *, token_hash: str, user_id: str) -> tuple[OrgRow, MembershipRow]:
        """Join org via invite key. Fail closed on expired / exhausted / revoked.

        ``max_uses`` is enforced by a conditional ``UPDATE`` so concurrent
        redeems cannot over-admit under multi-writer backends.
        """
        uid = _normalize_user_id(user_id) or user_id
        with self._connect() as conn:
            cur = self._exec(
                conn,
                Q.SELECT_INVITE_BY_HASH,
                (token_hash,),
            )
            r = cur.fetchone()
            if r is None:
                raise LookupError("invalid invite key")
            inv = self._invite_key_row(r)
            if inv.revoked_at is not None:
                raise PermissionError("invite key revoked")
            if inv.expires_at is not None and inv.expires_at <= now():
                raise PermissionError("invite key expired")
            org = self.get_org(inv.org_id)
            if org is None:
                raise LookupError("org not found")
            existing = self.membership(inv.org_id, uid)
            if existing is not None:
                # Already a member: do not burn use_count.
                return org, existing
            # Claim a slot atomically (check + increment). rowcount==0 ⇒ exhausted.
            claim = self._exec(
                conn,
                Q.CLAIM_INVITE_USE,
                (inv.key_id,),
            )
            if claim.rowcount == 0:
                raise PermissionError("invite key exhausted")
            ts = now()
            try:
                self._exec(
                    conn,
                    Q.INSERT_ORG_MEMBERSHIP_MEMBER,
                    (inv.org_id, uid, ts),
                )
            except self._adapter.integrity_error as exc:
                # Same-transaction rollback drops the claim on context exit.
                raise ValueError("membership exists") from exc
            conn.commit()
            mem = MembershipRow(org_id=inv.org_id, user_id=uid, role="member", created_at=ts)
            return org, mem

    @staticmethod
    def _invite_key_row(r: sqlite3.Row) -> OrgInviteKeyRow:
        max_uses = r["max_uses"]
        expires_at = r["expires_at"]
        revoked_at = r["revoked_at"]
        return OrgInviteKeyRow(
            key_id=str(r["key_id"]),
            org_id=str(r["org_id"]),
            token_hash=str(r["token_hash"]),
            token_prefix=str(r["token_prefix"] or ""),
            created_by=str(r["created_by"] or ""),
            max_uses=int(max_uses) if max_uses is not None else None,
            use_count=int(r["use_count"] or 0),
            expires_at=float(expires_at) if expires_at is not None else None,
            revoked_at=float(revoked_at) if revoked_at is not None else None,
            created_at=float(r["created_at"]),
        )

    def user_org_ids(self, user_id: str) -> set[str]:
        with self._connect() as conn:
            cur = self._exec(conn, Q.SELECT_USER_ORG_IDS, (user_id,))
            return {str(r["org_id"]) for r in cur.fetchall()}

    # ---- result shares ---------------------------------------------------

    def add_result_share(
        self,
        *,
        result_kind: str,
        result_id: str,
        target_type: str,
        target_id: str,
    ) -> ResultShareRow:
        if result_kind not in {"attempt", "suite"}:
            raise ValueError("invalid result_kind")
        if target_type not in {"org", "user"}:
            raise ValueError("invalid target_type")
        ts = now()
        with self._connect() as conn:
            try:
                self._exec(
                    conn,
                    Q.INSERT_RESULT_SHARE,
                    (result_kind, result_id, target_type, target_id, ts),
                )
                conn.commit()
            except self._adapter.integrity_error as exc:
                raise ValueError("share already exists") from exc
        return ResultShareRow(
            result_kind=result_kind,
            result_id=result_id,
            target_type=target_type,
            target_id=target_id,
            created_at=ts,
        )

    def remove_result_share(
        self,
        *,
        result_kind: str,
        result_id: str,
        target_type: str,
        target_id: str,
    ) -> None:
        with self._connect() as conn:
            cur = self._exec(
                conn,
                Q.DELETE_RESULT_SHARE,
                (result_kind, result_id, target_type, target_id),
            )
            if cur.rowcount == 0:
                raise LookupError("share not found")
            conn.commit()

    def list_result_shares(self, *, result_kind: str, result_id: str) -> list[ResultShareRow]:
        with self._connect() as conn:
            cur = self._exec(
                conn,
                Q.SELECT_RESULT_SHARES,
                (result_kind, result_id),
            )
            return [
                ResultShareRow(
                    result_kind=str(r["result_kind"]),
                    result_id=str(r["result_id"]),
                    target_type=str(r["target_type"]),
                    target_id=str(r["target_id"]),
                    created_at=float(r["created_at"]),
                )
                for r in cur.fetchall()
            ]

    def result_shared_with_user(
        self,
        *,
        result_kind: str,
        result_id: str,
        user_id: str,
        user_orgs: set[str],
    ) -> bool:
        with self._connect() as conn:
            cur = self._exec(
                conn,
                Q.SELECT_RESULT_SHARED_USER,
                (result_kind, result_id, user_id),
            )
            if cur.fetchone() is not None:
                return True
            if not user_orgs:
                return False
            orgs = sorted(user_orgs)
            cur = self._exec(
                conn,
                Q.select_result_shared_orgs_query(len(orgs)),
                (result_kind, result_id, *orgs),
            )
            return cur.fetchone() is not None

    @staticmethod
    def _org_row(r: sqlite3.Row) -> OrgRow:
        return OrgRow(
            org_id=str(r["org_id"]),
            name=str(r["name"]),
            display_name=str(r["display_name"] or ""),
            is_claimable=bool(int(r["is_claimable"])),
            created_at=float(r["created_at"]),
        )

    def upsert_user_profile(
        self,
        *,
        user_id: str,
        display_name: str = "",
        avatar_url: str = "",
        github_id: str = "",
    ) -> UserProfileRow:
        uid = _normalize_user_id(user_id) or user_id
        row = UserProfileRow(
            user_id=uid,
            display_name=(display_name or "").strip(),
            avatar_url=(avatar_url or "").strip(),
            github_id=str(github_id or "").strip(),
            updated_at=now(),
        )
        with self._connect() as conn:
            self._exec(
                conn,
                Q.UPSERT_USER_PROFILE,
                (
                    row.user_id,
                    row.display_name,
                    row.avatar_url,
                    row.github_id,
                    row.updated_at,
                ),
            )
            conn.commit()
        return row

    def get_user_profile(self, user_id: str) -> UserProfileRow | None:
        uid = _normalize_user_id(user_id) or user_id
        with self._connect() as conn:
            cur = self._exec(
                conn,
                Q.SELECT_USER_PROFILE,
                (uid,),
            )
            r = cur.fetchone()
            if r is None:
                return None
            return UserProfileRow(
                user_id=str(r["user_id"]),
                display_name=str(r["display_name"] or ""),
                avatar_url=str(r["avatar_url"] or ""),
                github_id=str(r["github_id"] or ""),
                updated_at=float(r["updated_at"]),
            )

    def get_user_profiles(self, user_ids: list[str] | set[str]) -> dict[str, UserProfileRow]:
        ids = sorted({_normalize_user_id(u) or u for u in user_ids if u})
        if not ids:
            return {}
        with self._connect() as conn:
            cur = self._exec(
                conn,
                Q.select_user_profiles_in_query(len(ids)),
                ids,
            )
            out: dict[str, UserProfileRow] = {}
            for r in cur.fetchall():
                p = UserProfileRow(
                    user_id=str(r["user_id"]),
                    display_name=str(r["display_name"] or ""),
                    avatar_url=str(r["avatar_url"] or ""),
                    github_id=str(r["github_id"] or ""),
                    updated_at=float(r["updated_at"]),
                )
                out[p.user_id] = p
            return out


class PostgresMetadataStore(MetadataStore):
    """Postgres metadata: same repository, thin dialect adapter."""

    def __init__(self, database_url: str) -> None:
        from services.registry.sql_adapter import PostgresAdapter

        MetadataStore.__init__(self, adapter=PostgresAdapter(database_url))
        self.database_url = database_url


def package_kind_for_media_type(media_type: str) -> str:
    """Derive list/meta ``package_kind`` without opening the blob."""
    try:
        from bora.registry.plugin_package import PLUGIN_MEDIA_TYPE

        if media_type == PLUGIN_MEDIA_TYPE:
            return "plugin"
    except Exception:  # noqa: BLE001 — kind is best-effort for clients
        pass
    return "database"


def release_to_dict(row: ReleaseRow) -> dict[str, Any]:
    out: dict[str, Any] = {
        "database_id": row.database_id,
        "version": row.version,
        "visibility": row.visibility,
        "package_digest": row.package_digest,
        "blob_digest": row.blob_digest,
        "size": row.size,
        "media_type": row.media_type,
        "package_kind": package_kind_for_media_type(row.media_type),
        "created_at": row.created_at,
    }
    if row.org_id:
        out["org_id"] = row.org_id
    if row.version == "draft":
        out["slot"] = "draft"
        out["is_draft"] = True
    return out


def attempt_to_dict(row: AttemptResultRow) -> dict[str, Any]:
    out: dict[str, Any] = {
        "run_id": row.run_id,
        "database_id": row.database_id,
        "task_id": row.task_id,
        "lock_digest": row.lock_digest,
        "status": row.status,
        "visibility": row.visibility,
        "blob_digest": row.blob_digest,
        "size": row.size,
        "created_at": row.created_at,
    }
    if row.uploaded_by:
        out["uploaded_by"] = row.uploaded_by
    if row.suite_run_id:
        out["suite_run_id"] = row.suite_run_id
    return out


def org_to_dict(row: OrgRow) -> dict[str, Any]:
    return {
        "org_id": row.org_id,
        "name": row.name,
        "display_name": row.display_name,
        "is_claimable": row.is_claimable,
        "created_at": row.created_at,
    }


def membership_to_dict(
    row: MembershipRow,
    *,
    profile: UserProfileRow | None = None,
) -> dict[str, Any]:
    out: dict[str, Any] = {
        "org_id": row.org_id,
        "user_id": row.user_id,
        "role": row.role,
        "created_at": row.created_at,
    }
    if profile is not None:
        if profile.display_name:
            out["display_name"] = profile.display_name
        if profile.avatar_url:
            out["avatar_url"] = profile.avatar_url
        if profile.github_id:
            out["github_id"] = profile.github_id
    return out


def invite_key_to_dict(
    row: OrgInviteKeyRow,
    *,
    invite_key: str | None = None,
) -> dict[str, Any]:
    """Serialize invite key metadata for owner APIs.

    Pass ``invite_key`` only on create so the secret is returned once.
    List/revoke omit it; storage keeps hash + prefix only.
    """
    out: dict[str, Any] = {
        "key_id": row.key_id,
        "org_id": row.org_id,
        "token_prefix": row.token_prefix,
        "created_by": row.created_by,
        "max_uses": row.max_uses,
        "use_count": row.use_count,
        "expires_at": row.expires_at,
        "revoked_at": row.revoked_at,
        "created_at": row.created_at,
        "active": row.revoked_at is None
        and (row.expires_at is None or row.expires_at > now())
        and (row.max_uses is None or row.use_count < row.max_uses),
    }
    if invite_key:
        out["invite_key"] = invite_key
    return out


def share_to_dict(row: ResultShareRow) -> dict[str, Any]:
    return {
        "result_kind": row.result_kind,
        "result_id": row.result_id,
        "target_type": row.target_type,
        "target_id": row.target_id,
        "created_at": row.created_at,
    }


def suite_to_dict(
    row: SuiteResultRow,
    *,
    attempt_content_ids: set[str] | None = None,
) -> dict[str, Any]:
    """Serialize suite result; never invent a suite-level PASS field.

    When *attempt_content_ids* is provided, each task_ref gains
    ``has_attempt_content`` (bool) for Hub Jobs deep-link readiness (#43).
    Callers must pass only attempt ids visible to the current principal
    (never invent true for private/unshared rows).
    """
    try:
        metrics = json.loads(row.metrics_json)
    except (json.JSONDecodeError, TypeError):
        metrics = {}
    try:
        task_refs = json.loads(row.tasks_json)
    except (json.JSONDecodeError, TypeError):
        task_refs = []
    if not isinstance(metrics, dict):
        metrics = {}
    if not isinstance(task_refs, list):
        task_refs = []
    if attempt_content_ids is not None:
        enriched: list[Any] = []
        for ref in task_refs:
            if not isinstance(ref, dict):
                enriched.append(ref)
                continue
            item = dict(ref)
            rid = item.get("run_id")
            rid_s = str(rid).strip() if rid is not None else ""
            item["has_attempt_content"] = bool(rid_s and rid_s in attempt_content_ids)
            enriched.append(item)
        task_refs = enriched
    out: dict[str, Any] = {
        "suite_run_id": row.suite_run_id,
        "database_id": row.database_id,
        "database_version": row.database_version,
        "visibility": row.visibility,
        "pass_rate": row.pass_rate,
        "mean_score": row.mean_score,
        "metrics": metrics,
        "task_refs": task_refs,
        "agent_label": row.agent_label,
        "model_label": row.model_label,
        "blob_digest": row.blob_digest,
        "size": row.size,
        "exit_code": row.exit_code,
        "created_at": row.created_at,
        "complete": bool(row.complete),
        "bound_kind": row.bound_kind or "unknown",
        # Explicit: no suite PASS authority
        "note": "per-task evaluator verdicts only; no suite-level PASS",
    }
    if row.task_set_digest:
        out["task_set_digest"] = row.task_set_digest
    if row.uploaded_by:
        out["uploaded_by"] = row.uploaded_by
    # #42 config fingerprint projection (absent on legacy rows)
    try:
        cfg = json.loads(row.config_json or "{}")
    except (json.JSONDecodeError, TypeError):
        cfg = {}
    if isinstance(cfg, dict):
        if cfg.get("config_fingerprint"):
            out["config_fingerprint"] = cfg["config_fingerprint"]
        if "config_homogeneous" in cfg:
            out["config_homogeneous"] = bool(cfg["config_homogeneous"])
        actors = cfg.get("actors_summary")
        if isinstance(actors, list):
            out["actors_summary"] = actors
        # #59 secret-free job binding for Hub rehydrate
        overlay = cfg.get("job_overlay")
        if isinstance(overlay, dict) and overlay:
            out["job_overlay"] = overlay
    return out


def _run_ids_from_tasks_json(tasks_json: str) -> list[str]:
    try:
        refs = json.loads(tasks_json)
    except (json.JSONDecodeError, TypeError):
        return []
    if not isinstance(refs, list):
        return []
    out: list[str] = []
    for ref in refs:
        if not isinstance(ref, dict):
            continue
        rid = ref.get("run_id")
        if rid is None:
            continue
        text = str(rid).strip()
        if text:
            out.append(text)
    return out


def now() -> float:
    return time.time()
