"""Package store protocol."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Protocol, runtime_checkable

if TYPE_CHECKING:
    from services.registry.packages.rows import DatasetAclRow, DraftRow, ReleaseRow


@runtime_checkable
class PackageStoreProtocol(Protocol):
    def insert(self, row: ReleaseRow) -> None: ...

    def get_by_version(self, dataset_id: str, version: str) -> ReleaseRow | None: ...

    def get_by_digest(self, dataset_id: str, package_digest: str) -> ReleaseRow | None: ...

    def list_releases(
        self,
        *,
        dataset_id_prefix: str | None = None,
        visibility: str | None = None,
        version: str | None = None,
        include_private: bool = False,
    ) -> list[ReleaseRow]: ...

    def list_versions(
        self, dataset_id: str, *, include_private: bool = False
    ) -> list[ReleaseRow]: ...

    def put_package_task_summary(
        self,
        package_digest: str,
        *,
        has_shared: bool,
        tasks: list[dict[str, Any]],
        overlay_prefixes: list[str],
        description: str = "",
    ) -> None: ...

    def package_task_counts(self, digests: list[str]) -> dict[str, int]: ...

    def package_manifest_descriptions(self, digests: list[str]) -> dict[str, str]: ...

    def get_package_task_summary(
        self, package_digest: str
    ) -> tuple[list[dict[str, Any]], bool, list[str]] | None: ...

    def delete_package_task_summary(self, package_digest: str) -> None: ...

    def count_package_digest_refs(self, package_digest: str) -> int: ...

    def count_package_blob_refs(self, blob_digest: str) -> int: ...

    def list_suite_task_refs(self, dataset_id: str) -> list[dict[str, Any]]: ...

    def delete_release(self, dataset_id: str, version: str) -> ReleaseRow: ...

    def set_release_visibility(
        self, dataset_id: str, version: str, visibility: str
    ) -> ReleaseRow: ...

    def upsert_draft(self, row: DraftRow) -> DraftRow: ...

    def get_draft(self, dataset_id: str) -> DraftRow | None: ...

    def get_draft_by_digest(self, dataset_id: str, package_digest: str) -> DraftRow | None: ...

    def list_drafts(self) -> list[DraftRow]: ...

    def delete_draft(self, dataset_id: str) -> DraftRow: ...

    def upsert_dataset_acl(
        self, dataset_id: str, user_id: str, *, role: str, created_at: float | None = None
    ) -> DatasetAclRow: ...

    def dataset_acl(self, dataset_id: str, user_id: str) -> DatasetAclRow | None: ...

    def list_dataset_acl(self, dataset_id: str) -> list[DatasetAclRow]: ...

    def list_dataset_acl_for_user(self, user_id: str) -> list[DatasetAclRow]: ...

    def set_package_display_name(self, dataset_id: str, display_name: str) -> str: ...

    def get_package_display_name(self, dataset_id: str) -> str: ...

    def package_display_names(self) -> dict[str, str]: ...

    def set_package_description(self, dataset_id: str, description: str) -> str: ...

    def get_package_description(self, dataset_id: str) -> str: ...

    def package_descriptions(self) -> dict[str, str]: ...

    def set_package_icon(
        self, dataset_id: str, *, icon_key: str, icon_github: str
    ) -> tuple[str, str]: ...

    def get_package_icon(self, dataset_id: str) -> tuple[str, str]: ...

    def package_icons(self) -> dict[str, tuple[str, str]]: ...

    def increment_package_download(self, dataset_id: str) -> None: ...

    def package_download_counts(self, dataset_ids: list[str] | set[str]) -> dict[str, int]: ...

    def add_package_favorite(self, user_id: str, dataset_id: str) -> None: ...

    def remove_package_favorite(self, user_id: str, dataset_id: str) -> None: ...

    def package_favorite_counts(self, dataset_ids: list[str] | set[str]) -> dict[str, int]: ...

    def package_favorites_for_user(
        self, user_id: str, dataset_ids: list[str] | set[str]
    ) -> set[str]: ...
