import type { SiteLocale } from "@/lib/i18n";

export const landingCopy = {
  "zh-CN": {
    metaTitle: "ageval · 把 Harness 作为一等评测维度",
    metaDescription:
      "大多数 Agent 评测仍停留在模型层面。ageval 把 Harness 作为一等评测维度，与 Model、运行环境一并锁定。Environment 与 Agent 经插件组合，同一份 run.py 在不同绑定下运行。",
    skip: "跳到正文",
    navAria: "页面导航",
    nav: {
      problem: "问题",
      core: "内核",
      isolation: "环境",
      eval: "评测",
      plugin: "插件",
      faq: "FAQ",
      docs: "文档",
      menu: "目录",
      repo: "仓库",
      lang: "EN",
    },
    hero: {
      titleA: "Agent 评测写一次，",
      titleB: "到处都能跑，比如",
      note: "ageval 是 harness 之下的 harness——一份题包，所有绑定，零改写。",
      primary: "打开仓库",
      hub: "前往 Hub",
      secondary: "阅读文档",
      startAria: "快速开始",
      startLabel: "快速开始",
      copy: "复制",
      copied: "已复制",
    },
    pactAria: "三条设计口令",
    pact: [
      ["HARD BOUNDARY", "边界硬", "时间、内存、进程、调用配额，执行前锁定。"],
      ["THIN CONTRACT", "契约薄", "Core 只管配置、环境、能力与评测。"],
      ["FAT IMPLEMENTATION", "实现自由", "loop、角色、本地 Tool 留在 run.py。"],
    ] as const,
    problem: {
      index: "// 01",
      name: "The Problem",
      title: ["评测仍停留在模型层面。", "这一划分正在失效。"],
      items: [
        [
          "01 / MODEL",
          "模型层评测",
          "同一套提示、同一套工具约定，比较不同权重或不同 API。",
        ],
        [
          "02 / HARNESS",
          "Agent 是组合",
          "可交付的 Agent 是 Model 与 Harness 的组合。",
        ],
        [
          "03 / DRIFT",
          "行为与成本都会变",
          "同一套权重接到不同的 coding-agent 运行时、工具策略或环境隔离上，行为与成本都会变。",
        ],
        [
          "04 / AXIS",
          "一等评测维度",
          "要把 Harness 作为一等评测维度，与 Model、运行环境一并锁定。",
        ],
      ] as const,
      solLabel: "SOLUTION →",
      sol: "把一次 bench 的 runtime 组成拆开：Environment 与 Agent 经插件组合",
    },
    position: {
      index: "// 02",
      name: "Positioning",
      title: "ageval 把 Harness 作为一等评测维度。",
      lead: "Environment 与 Agent 经插件组合，同一份 run.py 在不同绑定下运行。题包拥有 loop；runtime 拥有 lock、环境、评分与 cleanup。",
      ownedLabel: "OWNED · ageval 统一",
      owned: "lock、可见 Attempt、Environment 服务、评分屏障、evidence、cleanup。",
      ownedNote: "ageval.yaml · task.yaml · profiles.yaml",
      notLabel: "NOT OWNED · 留给题包",
      not: "loop、角色、本地 Tool 全部留在 run.py。",
      notNote: "loop · 角色 · 本地 Tool",
    },
    principles: {
      index: "// 03",
      name: "Principles",
      title: "边界硬，契约薄，实现自由。",
      items: [
        ["边界硬", "资源上限由 Runtime 在执行前强制。run.py 自己改不了。"],
        ["契约薄", "Core 只锁定配置、身份、环境与评测。契约里没有 workflow。"],
        ["实现自由", "复杂实现下沉到 run.py，不进 YAML 工作流引擎。"],
      ] as const,
      bannerEn: ["Hard boundaries.", "Thin contracts.", "Fat implementations."],
      bannerZh: "把一次 bench 的 runtime 组成拆开。",
    },
    core: {
      index: "// 04",
      name: "Core",
      title: "可见 Attempt，再加一层证据。",
      lead: "Core 拥有机制，题包拥有业务。",
      items: [
        ["CORE_01", "Config", "load_and_lock：digest。Lock 里没有密钥明文。", "CORE OWNS", false],
        ["CORE_02", "Attempt", "environment → run → evaluate → record；finally cleanup。", "CORE OWNS", false],
        [
          "CORE_03",
          "Environment",
          "按名注入：local / docker / e2b / ssh / daytona。",
          "CORE OWNS",
          false,
        ],
        ["CORE_04", "Capability", "requires ⊆ capabilities，缺则 lock 失败。", "NARROW SURFACE", true],
        ["CORE_05", "Evaluation", "停写，再 upload gold，独立打分后绑定。", "CORE OWNS", false],
        ["CORE_06", "Evidence", "trajectory.jsonl。凭据先脱敏。", "CORE OWNS", false],
      ] as const,
    },
    isolation: {
      index: "// 05",
      name: "Environment",
      title: "本机、容器、云沙箱、远端，同一套 Protocol。",
      lead: "更换 kind 无需修改 run.py。Environment 按名注入；调用只打 Protocol。",
      items: [
        ["KIND · LOCAL", "本机目录", "真文件系统，子进程 worker。", "VERIFIED", false],
        ["KIND · DOCKER", "本机容器", "同一份 Dockerfile。gold 在 evaluate 才进环境。", "VERIFIED", true],
        [
          "KIND · E2B / SSH / DAYTONA",
          "云沙箱与远端",
          "编排在本机。凭证缺失时 preflight 失败。",
          "CODE COMPLETE",
          false,
        ],
      ] as const,
    },
    eval: {
      index: "// 06",
      name: "Barrier",
      title: "完成，不等于通过。",
      lead: "PASS 仅来自 evaluator.py。评分与 Agent 分离。",
      neLeft: "completed",
      neRight: "PASS",
      steps: [
        ["01 封场", "停掉还在写的进程。"],
        ["02 注入", "evaluation/ 此刻才 upload。"],
        ["03 绑定", "环境内跑 evaluator.py。cleanup 失败不改分数。"],
      ] as const,
    },
    plugin: {
      index: "// 07",
      name: "Plugin",
      title: "Coding agent 通过插件接入。",
      lead: "默认 ACP；异构 harness 同样经插件进入 runtime。开放 slot 以补充和替换 harness。",
      slots: [
        ["EXCL", "environment", "环境赢家。local / docker / e2b / ssh / daytona。"],
        ["EXCL", "executor", "默认 acp；亦可 nooa / dsh / miniswe。"],
        ["CHAIN", "ready / setup", "探测 ACP、跑 setup.sh。"],
        ["CHAIN", "trajectory", "采集映射。不发明分数。"],
        ["CHAIN", "cleanup", "报告。不能跳过拆环境。"],
        ["LOCK", "inject", "按名注入 environment，并 require 能力。缺则 lock 失败。"],
      ] as const,
    },
    pluginCode: {
      index: "// 08",
      name: "In Code",
      title: "Core 的协议，DSH 的样例",
      lead: "宿主只认槽位 id。未知槽 resolve 期 fail closed。",
      coreTag: "CORE · 槽位与协议",
      pluginTag: "PLUGIN · plugins/dsh",
      note: "插件填独占 / 链。任何扩展路径都不能发明 PASS。",
    },
    flow: {
      index: "// 09",
      name: "End to End",
      title: "ageval lock → run → result",
      steps: [
        ["01", "lock", "load_and_lock · digest"],
        ["02", "environment", "host.start · setup.sh"],
        ["03", "run", "run.py · ACP"],
        ["04", "evaluate", "upload gold · bind"],
        ["05", "record", "trajectory.jsonl"],
        ["06", "cleanup", "host.stop"],
        ["07", "result", "status · logs"],
      ] as const,
      traj: [
        ["A · VENDOR RAW", "后端原样保留。"],
        ["B · 中立事件", "ageval.trajectory.event/1：只做映射。"],
        ["C · TRAJECTORY.JSONL", "只有 evidence writer 能折叠。"],
      ] as const,
    },
    take: {
      tag: "LOCK THE BINDING",
      title: "与 Model、Harness、环境一并锁定。",
      body: "把一次 bench 的 runtime 组成拆开。",
      items: [
        ["01", "一等评测维度", "Harness 与 Model、运行环境一并锁定。"],
        [
          "02",
          "插件组合",
          "Environment 与 Agent 经插件组合，同一份 run.py 在不同绑定下运行。",
        ],
        ["03", "评分分离", "PASS 仅来自 evaluator.py。"],
      ] as const,
    },
    cta: {
      title: ["先锁定绑定，", "再比较分数。"],
      lead: "clone 仓库，跑 examples/journeys。公开入口以 ageval --help 为准。",
      primary: "打开仓库",
      hub: "前往 Hub",
      docs: "阅读文档",
    },
    faq: {
      index: "// 10",
      name: "FAQ",
      title: "常见问题",
      items: [
        [
          "ageval 评测的是模型吗？",
          "大多数评测仍停留在模型层面。ageval 把 Harness 作为一等评测维度，与 Model、运行环境一并锁定。",
        ],
        [
          "轨迹完整，是不是就算通过？",
          "不算。RunTerminal.completed 不等于 PASS。PASS 仅来自 evaluator.py。",
        ],
        [
          "local 和 docker 要写两套 run.py 吗？",
          "不用。更换的是 job 上的 Environment 绑定。",
        ],
        [
          "参考答案怎么保证 Agent 看不见？",
          "不 mount，evaluate 开始前才 upload。",
        ],
        [
          "插件能改分数吗？",
          "不能。",
        ],
      ] as const,
    },
    footer: {
      body: "ageval — agent eval。ZJU-REAL 维护。仓库：ZJU-REAL/ageval。",
      mark: "ZJU-REAL · ageval",
    },
  },
  en: {
    metaTitle: "ageval · Harness as a first-class eval axis",
    metaDescription:
      "Most agent evaluation still sits at the model. ageval treats Harness as a first-class eval axis, locked with the Model and the environment. Environment and Agent combine through plugins; one run.py runs under each binding.",
    skip: "Skip to content",
    navAria: "Page navigation",
    nav: {
      problem: "Problem",
      core: "Core",
      isolation: "Environment",
      eval: "Eval",
      plugin: "Plugin",
      faq: "FAQ",
      docs: "Docs",
      menu: "Menu",
      repo: "Repo",
      lang: "中文",
    },
    hero: {
      titleA: "Write your agent eval once.",
      titleB: "Run it anywhere like on",
      note: "ageval is the harness beneath the harnesses — one task package, every binding, zero rewrites.",
      primary: "Open repo",
      hub: "Go to Hub",
      secondary: "Read the docs",
      startAria: "Quick start",
      startLabel: "Quick start",
      copy: "Copy",
      copied: "Copied",
    },
    pactAria: "Three design slogans",
    pact: [
      ["HARD BOUNDARY", "Hard boundary", "Time, memory, processes, and call quotas lock first."],
      ["THIN CONTRACT", "Thin contract", "Core owns config, the environment, capability, and evaluation."],
      ["FAT IMPLEMENTATION", "Fat implementation", "Loop, roles, and local tools stay in run.py."],
    ] as const,
    problem: {
      index: "// 01",
      name: "The Problem",
      title: ["Evaluation still sits at the model.", "That split is failing."],
      items: [
        [
          "01 / MODEL",
          "Model-level eval",
          "Same prompts, same tool contract, different weights or APIs.",
        ],
        [
          "02 / HARNESS",
          "Agent is a combination",
          "A shippable agent is a Model plus a Harness.",
        ],
        [
          "03 / DRIFT",
          "Behavior and cost change",
          "The same weights on a different coding-agent runtime, tool policy, or isolation change behavior and cost.",
        ],
        [
          "04 / AXIS",
          "First-class axis",
          "Harness has to be a first-class eval axis, locked with the Model and the environment.",
        ],
      ] as const,
      solLabel: "SOLUTION →",
      sol: "Decouple the runtime of a bench run: Environment and Agent combine through plugins",
    },
    position: {
      index: "// 02",
      name: "Positioning",
      title: "ageval treats Harness as a first-class evaluation axis.",
      lead: "Environment and Agent combine through plugins, so one run.py runs under each binding. The task owns the loop; the runtime owns lock, environment, scoring, and cleanup.",
      ownedLabel: "OWNED · ageval",
      owned: "lock, visible Attempt, Environment service, scoring barrier, evidence, cleanup.",
      ownedNote: "ageval.yaml · task.yaml · profiles.yaml",
      notLabel: "NOT OWNED · the task",
      not: "loop, roles, local tools in run.py.",
      notNote: "loop · roles · tools",
    },
    principles: {
      index: "// 03",
      name: "Principles",
      title: "Hard boundaries. Thin contracts. Fat implementations.",
      items: [
        ["Hard boundary", "Ceilings are enforced before execution. run.py cannot lift them."],
        ["Thin contract", "Core locks config, identity, the environment, and evaluation. No workflow in the contract."],
        ["Fat implementation", "Complexity sinks into run.py, not a YAML workflow engine."],
      ] as const,
      bannerEn: ["Hard boundaries.", "Thin contracts.", "Fat implementations."],
      bannerZh: "Decouple the runtime of a bench run.",
    },
    core: {
      index: "// 04",
      name: "Core",
      title: "A visible Attempt, plus evidence.",
      lead: "Core owns mechanism. The dataset owns business.",
      items: [
        ["CORE_01", "Config", "load_and_lock. No secret plaintext.", "CORE OWNS", false],
        ["CORE_02", "Attempt", "environment → run → evaluate → record; finally cleanup.", "CORE OWNS", false],
        [
          "CORE_03",
          "Environment",
          "Injected by name: local / docker / e2b / ssh / daytona.",
          "CORE OWNS",
          false,
        ],
        ["CORE_04", "Capability", "requires ⊆ capabilities or lock fails.", "NARROW SURFACE", true],
        ["CORE_05", "Evaluation", "Stop writers, upload gold, bind once.", "CORE OWNS", false],
        ["CORE_06", "Evidence", "trajectory.jsonl. Credentials redacted.", "CORE OWNS", false],
      ] as const,
    },
    isolation: {
      index: "// 05",
      name: "Environment",
      title: "Host, container, cloud sandbox, remote — one Protocol.",
      lead: "Change the kind without rewriting run.py. Environment is injected by name; calls stay on the Protocol.",
      items: [
        ["KIND · LOCAL", "Host directory", "Real filesystem. Child-process worker.", "VERIFIED", false],
        ["KIND · DOCKER", "Local container", "Same Dockerfile. Gold arrives at evaluate.", "VERIFIED", true],
        [
          "KIND · E2B / SSH / DAYTONA",
          "Cloud sandbox and remote",
          "Orchestration stays local. Missing credentials fail preflight.",
          "CODE COMPLETE",
          false,
        ],
      ] as const,
    },
    eval: {
      index: "// 06",
      name: "Barrier",
      title: "Completed is not passed.",
      lead: "PASS comes only from evaluator.py. Scoring is separate from the Agent.",
      neLeft: "completed",
      neRight: "PASS",
      steps: [
        ["01 seal", "Stop writers."],
        ["02 materialize", "evaluation/ uploads now."],
        ["03 bind", "evaluator.py runs in the environment. Cleanup cannot rewrite the score."],
      ] as const,
    },
    plugin: {
      index: "// 07",
      name: "Plugin",
      title: "Coding agents enter through plugins.",
      lead: "Default is ACP; heterogeneous harnesses join the runtime through the same plugin path. Open slots extend or replace a harness.",
      slots: [
        ["EXCL", "environment", "Environment winner: local / docker / e2b / ssh / daytona."],
        ["EXCL", "executor", "Default acp; also nooa / dsh / miniswe."],
        ["CHAIN", "ready / setup", "Probe ACP, run setup.sh."],
        ["CHAIN", "trajectory", "Map events. Do not invent scores."],
        ["CHAIN", "cleanup", "Report. Cannot skip teardown."],
        ["LOCK", "inject", "Inject environment by name and require capabilities, or lock fails."],
      ] as const,
    },
    pluginCode: {
      index: "// 08",
      name: "In Code",
      title: "Core protocol, DSH as a sample",
      lead: "Unknown slots fail closed at resolve.",
      coreTag: "CORE · slots and protocol",
      pluginTag: "PLUGIN · plugins/dsh",
      note: "Plugins fill exclusive / chain slots. No extension path invents PASS.",
    },
    flow: {
      index: "// 09",
      name: "End to End",
      title: "ageval lock → run → result",
      steps: [
        ["01", "lock", "load_and_lock · digest"],
        ["02", "environment", "host.start · setup.sh"],
        ["03", "run", "run.py · ACP"],
        ["04", "evaluate", "upload gold · bind"],
        ["05", "record", "trajectory.jsonl"],
        ["06", "cleanup", "host.stop"],
        ["07", "result", "status · logs"],
      ] as const,
      traj: [
        ["A · VENDOR RAW", "Keep backend output as-is."],
        ["B · Neutral events", "ageval.trajectory.event/1 — translate only."],
        ["C · TRAJECTORY.JSONL", "Only the evidence writer folds."],
      ] as const,
    },
    take: {
      tag: "LOCK THE BINDING",
      title: "Lock Model, Harness, and environment together.",
      body: "Decouple the runtime of a bench run.",
      items: [
        ["01", "First-class axis", "Harness is locked with the Model and the environment."],
        [
          "02",
          "Plugin composition",
          "Environment and Agent combine through plugins; one run.py runs under each binding.",
        ],
        ["03", "Separate scoring", "PASS comes only from evaluator.py."],
      ] as const,
    },
    cta: {
      title: ["Lock the binding first.", "Then compare the scores."],
      lead: "Clone the repo. Run examples/journeys. Public entrypoints follow ageval --help.",
      primary: "Open repo",
      hub: "Go to Hub",
      docs: "Read the docs",
    },
    faq: {
      index: "// 10",
      name: "FAQ",
      title: "FAQ",
      items: [
        [
          "Does ageval evaluate the model?",
          "Most evaluation still sits at the model. ageval treats Harness as a first-class eval axis, locked with the Model and the environment.",
        ],
        [
          "Does a complete trajectory count as a pass?",
          "No. RunTerminal.completed is not PASS. PASS comes only from evaluator.py.",
        ],
        [
          "Do local and docker need two run.py files?",
          "No. Change the Environment binding on the job.",
        ],
        [
          "How do you keep gold invisible?",
          "Do not mount it. Upload it when evaluate starts.",
        ],
        [
          "Can a plugin change the score?",
          "No.",
        ],
      ] as const,
    },
    footer: {
      body: "ageval — agent eval. Maintained by ZJU-REAL. GitHub: ZJU-REAL/ageval.",
      mark: "ZJU-REAL · ageval",
    },
  },
} as const;

export type LandingCopy = (typeof landingCopy)[SiteLocale];
