import type { SiteLocale } from "@/lib/i18n";

export const landingCopy = {
  "zh-CN": {
    metaTitle: "ageval · 有边界的 Agent 评测运行时",
    metaDescription:
      "ageval 锁定 dataset、打开环境、跑 Attempt，再由独立 evaluator 出分。统一实验，不统一工作流。",
    skip: "跳到正文",
    navAria: "页面导航",
    nav: {
      problem: "问题",
      core: "内核",
      isolation: "环境",
      eval: "评测",
      plugin: "插件",
      faq: "FAQ",
      docs: "文档",
      menu: "目录",
      repo: "仓库",
      lang: "EN",
    },
    hero: {
      brand: "ageval",
      title: ["锁定题包，打开环境，", "让独立评测出分"],
      lead: "统一实验，不统一工作流。ageval 把 lock、可见 Attempt、环境 kind 和独立 evaluator 收成同一套契约。换 Agent 或换环境，分数仍然可比。",
      primary: "打开仓库",
      secondary: "阅读设计",
      stageAria: "ageval 锁定面",
      stagePkg: "examples/journeys",
      stagePhase: "load_and_lock",
      rows: [
        ["format", "ageval.task/1", "task_id · terminal-jsonl-agg"],
        ["lock", "Config 唯一入口", "合并、校验、规范化，算出 digest。Lock 里没有密钥明文。"],
        ["bound", "environment: local", "环境是独占槽。资源上限执行前强制。"],
        ["judge", "evaluator.py", "completed 不能发明 PASS。"],
      ] as const,
      foot: "公开入口以",
      help: "ageval --help",
      footAfter: "为准",
      footCmd: "uv run ageval lock examples/journeys --task terminal-jsonl-agg",
    },
    pactAria: "三条设计口令",
    pact: [
      ["HARD BOUNDARY", "边界硬", "时间、内存、进程、调用配额，执行前锁定。"],
      ["THIN CONTRACT", "契约薄", "Core 只管配置、环境、能力与评测。"],
      ["FAT IMPLEMENTATION", "实现自由", "loop、角色、本地 Tool 留在 run.py。"],
    ] as const,
    problem: {
      index: "// 01",
      name: "The Problem",
      title: ["换一个 Agent，", "分数就不可比。"],
      items: [
        ["01 / HARNESS", "私有 harness", "编排、隔离、可见性、评测边界散落在各家 vendor 的 harness 里。"],
        ["02 / COMPARE", "分数不可比", "换 coding agent 或换环境，结果就失去可比性。"],
        ["03 / REPRO", "复现困难", "准备、运行、评测、保存没有统一契约。"],
        ["04 / TRACE", "轨迹碎片化", "每家一套 trace，轨迹与评分混在一起。"],
      ] as const,
      solLabel: "SOLUTION →",
      sol: "统一实验的编排契约，而不是统一题包内部工作流",
    },
    position: {
      index: "// 02",
      name: "Positioning",
      title: "ageval 管环境和流水线，不管题怎么 loop。",
      lead: "给运行划边界。打开 attempt.py 能看见相位。Agent 评测的外层：lock、开环境、invoke、打分、存证、拆环境。",
      ownedLabel: "OWNED · ageval 统一",
      owned: "lock、可见 Attempt、独立 evaluator、evidence、cleanup。",
      ownedNote: "ageval.yaml · task.yaml · profiles.yaml",
      notLabel: "NOT OWNED · 留给题包",
      not: "loop、角色、本地 Tool 全部留在 run.py。",
      notNote: "loop · 角色 · 本地 Tool",
    },
    principles: {
      index: "// 03",
      name: "Principles",
      title: "边界硬，契约薄，实现自由。",
      items: [
        ["边界硬", "资源上限由 Runtime 在执行前强制。run.py 自己改不了。"],
        ["契约薄", "Core 只锁定配置、身份、环境与评测。契约里没有 workflow。"],
        ["实现自由", "复杂实现下沉到 run.py，不进 YAML 工作流引擎。"],
      ] as const,
      bannerEn: ["Hard boundaries.", "Thin contracts.", "Fat implementations."],
      bannerZh: "给运行划边界，给实现留自由。",
    },
    core: {
      index: "// 04",
      name: "Core",
      title: "可见 Attempt，再加一层证据。",
      lead: "Core 拥有机制，题包拥有业务。",
      items: [
        ["CORE_01", "Config", "load_and_lock：digest。Lock 里没有密钥明文。", "CORE OWNS", false],
        ["CORE_02", "Attempt", "environment → run → evaluate → record；finally cleanup。", "CORE OWNS", false],
        ["CORE_03", "Environment", "独占槽 environment：local / docker / e2b / ssh。", "CORE OWNS", false],
        ["CORE_04", "Capability", "requires ⊆ capabilities，缺则 lock 失败。", "NARROW SURFACE", true],
        ["CORE_05", "Evaluation", "停写，再 upload gold，独立打分后绑定。", "CORE OWNS", false],
        ["CORE_06", "Evidence", "trajectory.jsonl。凭据先脱敏。", "CORE OWNS", false],
      ] as const,
    },
    isolation: {
      index: "// 05",
      name: "Environment",
      title: "四种环境，同一 Protocol。",
      lead: "换 kind 不换 run.py。ACP 只拿 attach_stdio。",
      items: [
        ["KIND · LOCAL", "本机目录", "真文件系统，子进程 worker。", "VERIFIED", false],
        ["KIND · DOCKER", "本机容器", "同一份 Dockerfile。gold 在 evaluate 才进环境。", "VERIFIED", true],
        ["KIND · E2B / SSH", "云上环境", "编排在本机。缺钥 preflight 失败。ssh 分整机与远端容器。", "CODE COMPLETE", false],
      ] as const,
    },
    eval: {
      index: "// 06",
      name: "Barrier",
      title: "完成，不等于通过。",
      lead: "PASS 只来自独立 evaluator。",
      neLeft: "completed",
      neRight: "PASS",
      steps: [
        ["01 封场", "停掉还在写的进程。"],
        ["02 注入", "evaluation/ 此刻才 upload。"],
        ["03 绑定", "环境内跑 evaluator.py。cleanup 失败不改分数。"],
      ] as const,
    },
    plugin: {
      index: "// 07",
      name: "Plugin",
      title: "宿主定槽，插件填位。",
      lead: "ageval.plugin/1 按机制命名。链槽走 (ctx, value, nxt)，独占槽一个赢家。",
      slots: [
        ["EXCL", "environment", "环境赢家。local / docker / e2b / ssh。"],
        ["EXCL", "executor", "Agent 后端。常是 acp。"],
        ["CHAIN", "ready / setup", "探测 ACP、跑 setup.sh。"],
        ["CHAIN", "trajectory", "采集映射。不发明分数。"],
        ["CHAIN", "cleanup", "报告。不能跳过拆环境。"],
        ["LOCK", "inject", "ACP 要 attach_stdio。缺则 lock 失败。"],
      ] as const,
    },
    pluginCode: {
      index: "// 08",
      name: "In Code",
      title: "Core 的协议，DSH 的样例",
      lead: "宿主只认槽位 id。未知槽 resolve 期 fail closed。",
      coreTag: "CORE · 槽位与协议",
      pluginTag: "PLUGIN · plugins/dsh",
      note: "插件填独占 / 链。任何扩展路径都不能发明 PASS。",
    },
    flow: {
      index: "// 09",
      name: "End to End",
      title: "ageval lock → run → result",
      steps: [
        ["01", "lock", "load_and_lock · digest"],
        ["02", "environment", "host.start · setup.sh"],
        ["03", "run", "run.py · ACP"],
        ["04", "evaluate", "upload gold · bind"],
        ["05", "record", "trajectory.jsonl"],
        ["06", "cleanup", "host.stop"],
        ["07", "result", "status · logs"],
      ] as const,
      traj: [
        ["A · VENDOR RAW", "后端原样保留。"],
        ["B · 中立事件", "ageval.trajectory.event/1：只做映射。"],
        ["C · TRAJECTORY.JSONL", "只有 evidence writer 能折叠。"],
      ] as const,
    },
    take: {
      tag: "BOUND THE RUN",
      title: "Bound the run, not the agent.",
      body: "给运行划边界，给实现留自由。",
      items: [
        ["01", "可信来自边界", "PASS 只属于独立 evaluator。"],
        ["02", "换环境，契约不变", "四种 kind 同一 SDK 与 ACP inlet。"],
        ["03", "插件填槽", "ageval.plugin/1 按机制命名。"],
      ] as const,
    },
    cta: {
      title: ["先锁定实验，", "再比较分数。"],
      lead: "clone 仓库，跑 examples/journeys。公开入口以 ageval --help 为准。",
      primary: "打开仓库",
      docs: "阅读设计",
    },
    faq: {
      index: "// 10",
      name: "FAQ",
      title: "常见问题",
      items: [
        [
          "ageval 是又一个 Agent 吗？",
          "不是。它是评测运行时。题内部 loop 在 run.py。Coding agent 走 ACP。",
        ],
        [
          "轨迹完整，是不是就算通过？",
          "不算。RunTerminal.completed 不等于 PASS。",
        ],
        [
          "local 和 docker 要写两套 run.py 吗？",
          "不用。换的是 profiles 里的 environment。",
        ],
        [
          "参考答案怎么保证 Agent 看不见？",
          "不 mount，evaluate 开始前才 upload。",
        ],
        [
          "插件能改分数吗？",
          "不能。",
        ],
      ] as const,
    },
    footer: {
      body: "ageval — agent eval。ZJU-REAL 维护。仓库：ZJU-REAL/ageval。",
      mark: "ZJU-REAL · ageval",
    },
  },
  en: {
    metaTitle: "ageval · bounded agent evaluation",
    metaDescription:
      "ageval locks a dataset, opens an environment, runs an Attempt, and lets an independent evaluator own the score.",
    skip: "Skip to content",
    navAria: "Page navigation",
    nav: {
      problem: "Problem",
      core: "Core",
      isolation: "Environment",
      eval: "Eval",
      plugin: "Plugin",
      faq: "FAQ",
      docs: "Docs",
      menu: "Menu",
      repo: "Repo",
      lang: "中文",
    },
    hero: {
      brand: "ageval",
      title: ["Lock the dataset.", "Open an environment. Judge independently."],
      lead: "Unify the experiment, not the workflow. Swap the agent or the environment. Scores stay comparable.",
      primary: "Open repo",
      secondary: "Read the design",
      stageAria: "ageval lock surface",
      stagePkg: "examples/journeys",
      stagePhase: "load_and_lock",
      rows: [
        ["format", "ageval.task/1", "task_id · terminal-jsonl-agg"],
        ["lock", "Config is the only reader", "Merge, validate, digest. No secret plaintext."],
        ["bound", "environment: local", "The environment is an exclusive slot. Ceilings lock before execution."],
        ["judge", "evaluator.py", "completed cannot invent PASS."],
      ] as const,
      foot: "Public entrypoints follow",
      help: "ageval --help",
      footAfter: ".",
      footCmd: "uv run ageval lock examples/journeys --task terminal-jsonl-agg",
    },
    pactAria: "Three design slogans",
    pact: [
      ["HARD BOUNDARY", "Hard boundary", "Time, memory, processes, and call quotas lock first."],
      ["THIN CONTRACT", "Thin contract", "Core owns config, the environment, capability, and evaluation."],
      ["FAT IMPLEMENTATION", "Fat implementation", "Loop, roles, and local tools stay in run.py."],
    ] as const,
    problem: {
      index: "// 01",
      name: "The Problem",
      title: ["Swap the agent,", "and scores stop comparing."],
      items: [
        ["01 / HARNESS", "Private harness", "Orchestration and the eval barrier live in each vendor stack."],
        ["02 / COMPARE", "Scores do not compare", "Change the agent or the environment, and the result loses comparability."],
        ["03 / REPRO", "Hard to reproduce", "Prepare, run, score, and save have no shared contract."],
        ["04 / TRACE", "Fragmented traces", "Each vendor mixes trajectory and score."],
      ] as const,
      solLabel: "SOLUTION →",
      sol: "Unify the experiment contract, not the task-internal workflow",
    },
    position: {
      index: "// 02",
      name: "Positioning",
      title: "ageval owns the environment and the pipeline, not the loop.",
      lead: "Bound the run. Open attempt.py and see the phases.",
      ownedLabel: "OWNED · ageval",
      owned: "lock, visible Attempt, independent evaluator, evidence, cleanup.",
      ownedNote: "ageval.yaml · task.yaml · profiles.yaml",
      notLabel: "NOT OWNED · the task",
      not: "loop, roles, local tools in run.py.",
      notNote: "loop · roles · tools",
    },
    principles: {
      index: "// 03",
      name: "Principles",
      title: "Hard boundaries. Thin contracts. Fat implementations.",
      items: [
        ["Hard boundary", "Ceilings are enforced before execution. run.py cannot lift them."],
        ["Thin contract", "Core locks config, identity, the environment, and evaluation. No workflow in the contract."],
        ["Fat implementation", "Complexity sinks into run.py, not a YAML workflow engine."],
      ] as const,
      bannerEn: ["Hard boundaries.", "Thin contracts.", "Fat implementations."],
      bannerZh: "Bound the run. Leave implementation free.",
    },
    core: {
      index: "// 04",
      name: "Core",
      title: "A visible Attempt, plus evidence.",
      lead: "Core owns mechanism. The dataset owns business.",
      items: [
        ["CORE_01", "Config", "load_and_lock. No secret plaintext.", "CORE OWNS", false],
        ["CORE_02", "Attempt", "environment → run → evaluate → record; finally cleanup.", "CORE OWNS", false],
        ["CORE_03", "Environment", "Exclusive slot: local / docker / e2b / ssh.", "CORE OWNS", false],
        ["CORE_04", "Capability", "requires ⊆ capabilities or lock fails.", "NARROW SURFACE", true],
        ["CORE_05", "Evaluation", "Stop writers, upload gold, bind once.", "CORE OWNS", false],
        ["CORE_06", "Evidence", "trajectory.jsonl. Credentials redacted.", "CORE OWNS", false],
      ] as const,
    },
    isolation: {
      index: "// 05",
      name: "Environment",
      title: "Four kinds. One protocol.",
      lead: "Swap the kind. Keep run.py. ACP only sees attach_stdio.",
      items: [
        ["KIND · LOCAL", "Host directory", "Real filesystem. Child-process worker.", "VERIFIED", false],
        ["KIND · DOCKER", "Local container", "Same Dockerfile. Gold arrives at evaluate.", "VERIFIED", true],
        ["KIND · E2B / SSH", "Cloud environment", "Orchestration stays local. Missing keys fail preflight.", "CODE COMPLETE", false],
      ] as const,
    },
    eval: {
      index: "// 06",
      name: "Barrier",
      title: "Completed is not passed.",
      lead: "PASS comes only from an independent evaluator.",
      neLeft: "completed",
      neRight: "PASS",
      steps: [
        ["01 seal", "Stop writers."],
        ["02 materialize", "evaluation/ uploads now."],
        ["03 bind", "evaluator.py runs in the environment. Cleanup cannot rewrite the score."],
      ] as const,
    },
    plugin: {
      index: "// 07",
      name: "Plugin",
      title: "The host defines slots. Plugins fill them.",
      lead: "ageval.plugin/1 is named by mechanism. Chains are (ctx, value, nxt). Exclusive slots have one winner.",
      slots: [
        ["EXCL", "environment", "Environment winner: local / docker / e2b / ssh."],
        ["EXCL", "executor", "Agent backend, usually acp."],
        ["CHAIN", "ready / setup", "Probe ACP, run setup.sh."],
        ["CHAIN", "trajectory", "Map events. Do not invent scores."],
        ["CHAIN", "cleanup", "Report. Cannot skip teardown."],
        ["LOCK", "inject", "ACP needs attach_stdio or lock fails."],
      ] as const,
    },
    pluginCode: {
      index: "// 08",
      name: "In Code",
      title: "Core protocol, DSH as a sample",
      lead: "Unknown slots fail closed at resolve.",
      coreTag: "CORE · slots and protocol",
      pluginTag: "PLUGIN · plugins/dsh",
      note: "Plugins fill exclusive / chain slots. No extension path invents PASS.",
    },
    flow: {
      index: "// 09",
      name: "End to End",
      title: "ageval lock → run → result",
      steps: [
        ["01", "lock", "load_and_lock · digest"],
        ["02", "environment", "host.start · setup.sh"],
        ["03", "run", "run.py · ACP"],
        ["04", "evaluate", "upload gold · bind"],
        ["05", "record", "trajectory.jsonl"],
        ["06", "cleanup", "host.stop"],
        ["07", "result", "status · logs"],
      ] as const,
      traj: [
        ["A · VENDOR RAW", "Keep backend output as-is."],
        ["B · Neutral events", "ageval.trajectory.event/1 — translate only."],
        ["C · TRAJECTORY.JSONL", "Only the evidence writer folds."],
      ] as const,
    },
    take: {
      tag: "BOUND THE RUN",
      title: "Bound the run, not the agent.",
      body: "Bound the run. Leave implementation free.",
      items: [
        ["01", "Trust comes from the boundary", "PASS belongs only to the evaluator."],
        ["02", "Swap the environment. Keep the contract.", "Four kinds, one SDK and ACP inlet."],
        ["03", "Plugins fill slots", "ageval.plugin/1 is named by mechanism."],
      ] as const,
    },
    cta: {
      title: ["Lock the experiment first.", "Then compare the scores."],
      lead: "Clone the repo. Run examples/journeys. Public entrypoints follow ageval --help.",
      primary: "Open repo",
      docs: "Read the design",
    },
    faq: {
      index: "// 10",
      name: "FAQ",
      title: "FAQ",
      items: [
        [
          "Is ageval another agent?",
          "No. It is an evaluation runtime. The task loop lives in run.py. Coding agents enter via ACP.",
        ],
        [
          "Does a complete trajectory count as a pass?",
          "No. RunTerminal.completed is not PASS.",
        ],
        [
          "Do local and docker need two run.py files?",
          "No. Change environment on the profiles document.",
        ],
        [
          "How do you keep gold invisible?",
          "Do not mount it. Upload it when evaluate starts.",
        ],
        [
          "Can a plugin change the score?",
          "No.",
        ],
      ] as const,
    },
    footer: {
      body: "ageval — agent eval. Maintained by ZJU-REAL. GitHub: ZJU-REAL/ageval.",
      mark: "ZJU-REAL · ageval",
    },
  },
} as const;

export type LandingCopy = (typeof landingCopy)[SiteLocale];
