import type { SiteLocale } from "@/lib/i18n";

export const landingCopy = {
  "zh-CN": {
    metaTitle: "ageval · 一份 dataset，到处都能跑",
    metaDescription:
      "一键切换待评测 Agent；装上 CLI 和 skill，让 Agent 学会自动评测；在 ageval Hub 上分享或复用 dataset、插件和 Agent 配置。",
    skip: "跳到正文",
    navAria: "页面导航",
    nav: {
      problem: "问题",
      core: "Core",
      isolation: "环境",
      eval: "自动评测",
      plugin: "插件",
      faq: "FAQ",
      docs: "文档",
      menu: "目录",
      repo: "仓库",
      lang: "EN",
    },
    hero: {
      titleA: "Agent 评测写一次，",
      titleB: "到处都能跑，比如",
      note: "装插件换待评测 Agent。装上 CLI 和 skill，Agent 能自己跑评测。",
      primary: "打开仓库",
      hub: "前往 Hub",
      secondary: "阅读文档",
      startAria: "快速开始",
      startLabel: "快速开始",
      copy: "复制",
      copied: "已复制",
    },
    pactAria: "三个特点",
    pact: [
      ["SWITCH", "一键切换待评测 Agent", "为运行基座按需编写、安装插件，补上你的自定义能力。"],
      ["TEACH", "让 Agent 学会自动评测", "装上 CLI 和 skill，让 Agent 能设计、转化 benchmark，并自动跑评测。"],
      ["HUB", "在 Hub 上分享与复用", "在 ageval Hub 上分享或复用 dataset、插件和 Agent 配置，并上传评测结果。"],
    ] as const,
    problem: {
      index: "// 01",
      name: "The Problem",
      title: ["评测仍停留在模型层面。", "模型和运行时已经不是一回事。"],
      items: [
        [
          "01 / MODEL",
          "模型层评测",
          "同一套提示、同一套工具约定，比较不同权重或不同 API。",
        ],
        [
          "02 / RUNTIME",
          "Agent 是组合",
          "可交付的 Agent 是模型加上它的运行时。",
        ],
        [
          "03 / DRIFT",
          "行为与成本都会变",
          "同一套权重接到不同的 coding agent、工具策略或环境上，行为和成本都会变。",
        ],
        [
          "04 / RECORD",
          "分数要记下组合",
          "分数要带上用了哪个 Agent 运行时、哪套环境，不能只报模型名。",
        ],
      ] as const,
      solLabel: "SOLUTION →",
      sol: "为运行基座按需编写、安装插件，切换待评测 Agent",
    },
    position: {
      index: "// 02",
      name: "Positioning",
      title: "运行基座不动，装插件换 Agent。",
      lead: "为运行基座按需编写、安装插件，补上环境和 Agent 运行时。loop 写在 task 里；runtime 管 lock、环境、评分与 cleanup。",
      ownedLabel: "OWNED · ageval 统一",
      owned: "lock、一次运行的目录、环境、评分、evidence、cleanup。",
      ownedNote: "ageval.yaml · task.yaml · profiles.yaml",
      notLabel: "NOT OWNED · 留给 dataset",
      not: "loop、角色、本地 Tool 全部留在 run.py。",
      notNote: "loop · 角色 · 本地 Tool",
    },
    principles: {
      index: "// 03",
      name: "Use it",
      title: "一键切换。自动评测。Hub 上复用。",
      items: [
        ["一键切换待评测 Agent", "为运行基座按需编写、安装插件，补上你的自定义能力。"],
        ["让 Agent 学会自动评测", "装上 CLI 和 skill，让 Agent 能设计、转化 benchmark，并自动跑评测。"],
        ["在 Hub 上分享与复用", "在 ageval Hub 上分享或复用 dataset、插件和 Agent 配置，并上传评测结果。"],
      ] as const,
      bannerEn: ["Switch the agent under test.", "Teach the Agent to eval.", "Share and reuse on Hub."],
      bannerZh: "装插件换 Agent。让 Agent 自己跑评测。在 Hub 上复用。",
    },
    core: {
      index: "// 04",
      name: "Core",
      title: "每次运行都留下目录和轨迹。",
      lead: "Core 管机制，dataset 管这道题。",
      items: [
        ["CORE_01", "Config", "load_and_lock：digest。Lock 里没有密钥明文。", "CORE OWNS", false],
        ["CORE_02", "Run", "environment → run → evaluate → record；finally cleanup。", "CORE OWNS", false],
        [
          "CORE_03",
          "Environment",
          "本机 / Docker / e2b / ssh / daytona。",
          "CORE OWNS",
          false,
        ],
        ["CORE_04", "Capability", "缺了需要的能力，lock 失败。", "LOCK FAILS", false],
        ["CORE_05", "Evaluation", "停写，再 upload gold，独立打分后绑定。", "CORE OWNS", false],
        ["CORE_06", "Evidence", "目录里有 trajectory.jsonl。凭据先脱敏。", "CORE OWNS", false],
      ] as const,
    },
    isolation: {
      index: "// 05",
      name: "Environment",
      title: "本机、容器、云沙箱、远端。",
      lead: "环境和自定义能力用插件补上。本机、Docker、云沙箱、远端走同一套调用。",
      items: [
        ["ENV · LOCAL", "本机目录", "真文件系统，子进程 worker。", "VERIFIED", false],
        ["ENV · DOCKER", "本机容器", "同一份 Dockerfile。gold 在 evaluate 才进环境。", "VERIFIED", true],
        [
          "ENV · E2B / SSH / DAYTONA",
          "云沙箱与远端",
          "编排在本机。凭证缺失时 preflight 失败。",
          "CODE COMPLETE",
          false,
        ],
      ] as const,
    },
    eval: {
      index: "// 06",
      name: "Auto",
      title: "让 Agent 学会自动评测。",
      lead: "装上 CLI 和 skill，Agent 能设计、转化 benchmark，并自动跑评测。",
      neLeft: "人盯着跑",
      neRight: "Agent 自动跑",
      steps: [
        ["01 CLI", "uv tool install ageval-cli"],
        ["02 skill", "npx skills add ZJU-REAL/ageval"],
        ["03 跑评测", "Agent 设计、转化 benchmark，并自动跑完。"],
      ] as const,
    },
    plugin: {
      index: "// 07",
      name: "Plugin",
      title: "一键切换待评测 Agent。",
      lead: "为运行基座按需编写、安装插件，补上你的自定义能力。",
      slots: [
        ["ENV", "environment", "本机 / Docker / e2b / ssh / daytona。用插件补环境，不用改基座。"],
        ["AGENT", "executor", "默认 acp（pi / Codex / Claude Code / OpenCode）；也可 nooa / dsh / miniswe。"],
        ["SETUP", "setup", "有 setup.sh 就在环境里跑。"],
        ["TRAJ", "trajectory", "记下过程。不决定 PASS。"],
        ["CLEAN", "cleanup", "拆环境。失败也不改分数。"],
        ["LOCK", "lock", "缺能力或缺凭证，lock 失败，不会开始跑。"],
      ] as const,
    },
    pluginCode: {
      index: "// 08",
      name: "In Code",
      title: "Core 的协议，DSH 的样例",
      lead: "缺了需要的能力，lock 就失败。",
      coreTag: "CORE · 环境和 Agent 入口",
      pluginTag: "PLUGIN · plugins/dsh",
      note: "插件补上自定义能力。换待评测 Agent 不用改基座。",
    },
    flow: {
      index: "// 09",
      name: "End to End",
      title: "ageval lock → run → result",
      steps: [
        ["01", "lock", "load_and_lock · digest"],
        ["02", "environment", "host.start · setup.sh"],
        ["03", "run", "run.py · ACP"],
        ["04", "evaluate", "upload gold · bind"],
        ["05", "record", "trajectory.jsonl"],
        ["06", "cleanup", "host.stop"],
        ["07", "result", "status · logs"],
      ] as const,
      traj: [
        ["A · VENDOR RAW", "后端原样保留。"],
        ["B · 中立事件", "ageval.trajectory.event/1：只做映射。"],
        ["C · TRAJECTORY.JSONL", "只有 evidence writer 能折叠。"],
      ] as const,
    },
    take: {
      tag: "THREE",
      title: "切换 Agent。自动评测。Hub 上复用。",
      body: "装插件换待评测 Agent。让 Agent 自己跑评测。在 Hub 上分享 dataset、插件和 Agent 配置。",
      items: [
        ["01", "一键切换待评测 Agent", "为运行基座按需编写、安装插件，补上你的自定义能力。"],
        [
          "02",
          "让 Agent 学会自动评测",
          "装上 CLI 和 skill，让 Agent 能设计、转化 benchmark，并自动跑评测。",
        ],
        ["03", "在 Hub 上分享与复用", "在 ageval Hub 上分享或复用 dataset、插件和 Agent 配置，并上传评测结果。"],
      ] as const,
    },
    cta: {
      title: ["装上 CLI 和 skill，", "开始跑评测。"],
      lead: "uv tool install ageval-cli。公开入口以 ageval --help 为准。",
      primary: "打开仓库",
      hub: "前往 Hub",
      docs: "阅读文档",
    },
    faq: {
      index: "// 10",
      name: "FAQ",
      title: "常见问题",
      items: [
        [
          "怎么切换待评测的 Agent？",
          [
            "待评测的是 coding agent（pi、Codex、Claude Code、dsh 这类），不是只换一个模型名。ageval 的运行基座不动：按需编写、安装插件，把环境和 Agent 运行时补上去，再用配置切换。",
            "内置 Agent 包可以直接 --agent pi，不必先 install。自己的 overlays 包先 ageval agent install，再 --agent org/name@version。环境和绑定写在 profiles.yaml，不写进 dataset。换 Agent 不用 fork 框架。",
          ],
        ],
        [
          "装上 CLI 之后，怎么让本机 Agent 自己跑评测？",
          [
            "uv tool install ageval-cli，再 npx skills add ZJU-REAL/ageval。skill 会告诉你的 coding agent 怎么调用 lock / run，以及怎么写 dataset。之后可以由 Agent 设计或转化 benchmark，并自动跑评测。",
            "跑真的 coding agent 还需要本机 ACP 入口和凭据；只做 ageval lock 检查配置时不需要。缺 extras 或凭据时，检查不过就不会开始跑，报错里会写该装什么。",
          ],
        ],
        [
          "Hub 上的 dataset 怎么跑？结果怎么分享？",
          [
            "ageval registry list 查看当前可见的 dataset，然后 ageval run <org>/<name>@<version>。也可以直接跑本地 dataset 根目录。默认 profiles 用 environment: docker，需要本机有可用的 Docker 引擎。",
            "dataset、插件和 Agent 配置都可以在 ageval Hub 上分享或复用，评测结果也可以上传。别人拿去是为了接着跑，不只是看一张分数表。本机用 ageval view 按 Jobs → Tasks 打开一次运行。",
          ],
        ],
        [
          "写一份 dataset 要准备哪些文件？",
          [
            "交付单位是 dataset。根目录放 ageval.yaml；每个 task 一个 tasks/<id>/，里面是 task.yaml、业务循环 run.py、评分 evaluator.py，以及 gold。环境和 Agent 写在 profiles.yaml，不要在 dataset 里绑死某一种运行时。",
            "loop、角色、本地 Tool 留在 task 里。lock、开环境、把分数绑上去、cleanup，由 ageval 管。SDK 可选，不决定 PASS，也不持有宿主凭据。",
          ],
        ],
        [
          "想接自己的环境或 Agent，插件怎么写？",
          [
            "给运行基座写插件，不要去改 ageval 源码。插件声明自己补的是环境还是 Agent 运行时，装上之后用配置切换。默认走 ACP；dsh、nooa、miniswe 也是同一类插件。",
            "插件声明的能力或凭证如果对不上，ageval lock 会失败，不会开始跑。",
          ],
        ],
        [
          "换成本机、Docker 或云沙箱，dataset 要重写吗？参考答案会进 Agent 能看见的目录吗？",
          [
            "不用重写 dataset。换环境改 profiles.yaml：本机、Docker，或 E2B / SSH / Daytona。同一份 task 在不同环境下跑。",
            "gold 放在 tasks/<id>/evaluation/。Agent 跑的时候不会把它 mount 进去；evaluate 阶段才 upload 到环境里打分。",
          ],
        ],
      ] as const,
    },
    footer: {
      body: "ageval — agent eval。ZJU-REAL 维护。仓库：ZJU-REAL/ageval。",
      mark: "ZJU-REAL · ageval",
    },
  },
  en: {
    metaTitle: "ageval · Write the eval once. Run it anywhere.",
    metaDescription:
      "Switch the agent under test with plugins. Teach the Agent automated evaluation with the CLI and skills. Share datasets, plugins, and agent configs on ageval Hub.",
    skip: "Skip to content",
    navAria: "Page navigation",
    nav: {
      problem: "Problem",
      core: "Core",
      isolation: "Environment",
      eval: "Auto eval",
      plugin: "Plugin",
      faq: "FAQ",
      docs: "Docs",
      menu: "Menu",
      repo: "Repo",
      lang: "中文",
    },
    hero: {
      titleA: "Write your agent eval once.",
      titleB: "Run it anywhere like on",
      note: "Swap the agent under test with plugins. Teach the Agent to run evals with the CLI and skills.",
      primary: "Open repo",
      hub: "Go to Hub",
      secondary: "Read the docs",
      startAria: "Quick start",
      startLabel: "Quick start",
      copy: "Copy",
      copied: "Copied",
    },
    pactAria: "Three things you can do",
    pact: [
      ["SWITCH", "Switch between Agents to be evaluated with one click", "Write and install plugins on demand for the running base to enhance your customization capabilities."],
      ["TEACH", "Teach the Agent automated evaluation", "Install CLI and skills so that the Agent can design, convert benchmarks, and automatically run evaluations."],
      ["HUB", "Share and reuse on Hub", "Share or reuse datasets, plugins and Agent configurations on ageval Hub, and upload evaluation results."],
    ] as const,
    problem: {
      index: "// 01",
      name: "The Problem",
      title: ["Evaluation still sits at the model.", "The model is not the runtime."],
      items: [
        [
          "01 / MODEL",
          "Model-level eval",
          "Same prompts, same tool contract, different weights or APIs.",
        ],
        [
          "02 / RUNTIME",
          "Agent is a combination",
          "A shippable agent is a model plus its runtime.",
        ],
        [
          "03 / DRIFT",
          "Behavior and cost change",
          "The same weights on a different coding agent, tool policy, or environment change behavior and cost.",
        ],
        [
          "04 / RECORD",
          "Record the combination",
          "A score has to name which agent runtime and which environment ran it, not only the model.",
        ],
      ] as const,
      solLabel: "SOLUTION →",
      sol: "Write and install plugins on the running base to switch the agent under test",
    },
    position: {
      index: "// 02",
      name: "Positioning",
      title: "Keep the running base. Swap Agent with plugins.",
      lead: "Write and install plugins on demand to add environment and agent-runtime support. The task owns the loop; the runtime owns lock, environment, scoring, and cleanup.",
      ownedLabel: "OWNED · ageval",
      owned: "lock, the Attempt directory, environment, scoring, evidence, cleanup.",
      ownedNote: "ageval.yaml · task.yaml · profiles.yaml",
      notLabel: "NOT OWNED · the dataset",
      not: "loop, roles, local tools in run.py.",
      notNote: "loop · roles · tools",
    },
    principles: {
      index: "// 03",
      name: "Use it",
      title: "Switch Agent. Teach eval. Share on Hub.",
      items: [
        ["Switch between Agents to be evaluated with one click", "Write and install plugins on demand for the running base to enhance your customization capabilities."],
        ["Teach the Agent automated evaluation", "Install CLI and skills so that the Agent can design, convert benchmarks, and automatically run evaluations."],
        ["Share and reuse on Hub", "Share or reuse datasets, plugins and Agent configurations on ageval Hub, and upload evaluation results."],
      ] as const,
      bannerEn: ["Switch the agent under test.", "Teach the Agent to eval.", "Share and reuse on Hub."],
      bannerZh: "Plugins. CLI and skills. Hub.",
    },
    core: {
      index: "// 04",
      name: "Core",
      title: "Each Attempt leaves a directory and a trajectory.",
      lead: "Core owns mechanism. The dataset owns the task.",
      items: [
        ["CORE_01", "Config", "load_and_lock. No secret plaintext.", "CORE OWNS", false],
        ["CORE_02", "Attempt", "environment → run → evaluate → record; finally cleanup.", "CORE OWNS", false],
        [
          "CORE_03",
          "Environment",
          "Host / Docker / e2b / ssh / daytona.",
          "CORE OWNS",
          false,
        ],
        ["CORE_04", "Capability", "Missing capability fails at lock.", "LOCK FAILS", false],
        ["CORE_05", "Evaluation", "Stop writers, upload gold, bind once.", "CORE OWNS", false],
        ["CORE_06", "Evidence", "trajectory.jsonl in the run directory. Credentials redacted.", "CORE OWNS", false],
      ] as const,
    },
    isolation: {
      index: "// 05",
      name: "Environment",
      title: "Host, container, cloud sandbox, remote.",
      lead: "Plugins add environment and custom capabilities. Host, Docker, cloud sandbox, and remote use the same calls.",
      items: [
        ["ENV · LOCAL", "Host directory", "Real filesystem. Child-process worker.", "VERIFIED", false],
        ["ENV · DOCKER", "Local container", "Same Dockerfile. Gold arrives at evaluate.", "VERIFIED", true],
        [
          "ENV · E2B / SSH / DAYTONA",
          "Cloud sandbox and remote",
          "Orchestration stays local. Missing credentials fail preflight.",
          "CODE COMPLETE",
          false,
        ],
      ] as const,
    },
    eval: {
      index: "// 06",
      name: "Auto",
      title: "Teach the Agent automated evaluation.",
      lead: "Install the CLI and skills so the Agent can design, convert benchmarks, and run evaluations.",
      neLeft: "you click through",
      neRight: "the Agent runs it",
      steps: [
        ["01 CLI", "uv tool install ageval-cli"],
        ["02 skill", "npx skills add ZJU-REAL/ageval"],
        ["03 run", "The Agent designs, converts, and runs the benchmark."],
      ] as const,
    },
    plugin: {
      index: "// 07",
      name: "Plugin",
      title: "Switch between Agents to be evaluated with one click.",
      lead: "Write and install plugins on demand for the running base to enhance your customization capabilities.",
      slots: [
        ["ENV", "environment", "Host / Docker / e2b / ssh / daytona. Add the environment with a plugin; do not change the base."],
        ["AGENT", "executor", "Default acp (pi / Codex / Claude Code / OpenCode); also nooa / dsh / miniswe."],
        ["SETUP", "setup", "If setup.sh exists, it runs in the environment."],
        ["TRAJ", "trajectory", "Record the process. Do not decide PASS."],
        ["CLEAN", "cleanup", "Tear down the environment. Failure does not rewrite the score."],
        ["LOCK", "lock", "Missing capability or credentials fail at lock. The run does not start."],
      ] as const,
    },
    pluginCode: {
      index: "// 08",
      name: "In Code",
      title: "Core protocol, DSH as a sample",
      lead: "Missing capability fails at lock.",
      coreTag: "CORE · environment and Agent inlet",
      pluginTag: "PLUGIN · plugins/dsh",
      note: "Plugins add custom capabilities. Switch the agent under test without changing the base.",
    },
    flow: {
      index: "// 09",
      name: "End to End",
      title: "ageval lock → run → result",
      steps: [
        ["01", "lock", "load_and_lock · digest"],
        ["02", "environment", "host.start · setup.sh"],
        ["03", "run", "run.py · ACP"],
        ["04", "evaluate", "upload gold · bind"],
        ["05", "record", "trajectory.jsonl"],
        ["06", "cleanup", "host.stop"],
        ["07", "result", "status · logs"],
      ] as const,
      traj: [
        ["A · VENDOR RAW", "Keep backend output as-is."],
        ["B · Neutral events", "ageval.trajectory.event/1 — translate only."],
        ["C · TRAJECTORY.JSONL", "Only the evidence writer folds."],
      ] as const,
    },
    take: {
      tag: "THREE",
      title: "Switch Agent. Teach eval. Share on Hub.",
      body: "Plugins swap the agent under test. The CLI and skills let the Agent run evals. Hub shares datasets, plugins, and agent configs.",
      items: [
        ["01", "Switch between Agents to be evaluated with one click", "Write and install plugins on demand for the running base to enhance your customization capabilities."],
        [
          "02",
          "Teach the Agent automated evaluation",
          "Install CLI and skills so that the Agent can design, convert benchmarks, and automatically run evaluations.",
        ],
        ["03", "Share and reuse on Hub", "Share or reuse datasets, plugins and Agent configurations on ageval Hub, and upload evaluation results."],
      ] as const,
    },
    cta: {
      title: ["Install the CLI and skills.", "Start running evals."],
      lead: "uv tool install ageval-cli. Public entrypoints follow ageval --help.",
      primary: "Open repo",
      hub: "Go to Hub",
      docs: "Read the docs",
    },
    faq: {
      index: "// 10",
      name: "FAQ",
      title: "FAQ",
      items: [
        [
          "How do I switch the agent under test?",
          [
            "The thing under test is a coding agent (pi, Codex, Claude Code, dsh), not a model name. The running base stays put: write and install plugins to add the environment and the agent runtime, then switch them in config.",
            "Built-in Agent packages bind with --agent pi (no install). Custom overlay packs use ageval agent install, then --agent org/name@version. Environment and bindings live in profiles.yaml, not in the dataset. You do not fork the framework to swap Agent.",
          ],
        ],
        [
          "After I install the CLI, how does my Agent run evals itself?",
          [
            "uv tool install ageval-cli, then npx skills add ZJU-REAL/ageval. The skill tells your coding agent how to call lock / run and how to write a dataset. From there the Agent can design or convert a benchmark and run the eval.",
            "A live coding-agent run still needs a host ACP entry and credentials. ageval lock alone does not. Missing extras or credentials fail the check and the run does not start; the error names the install command.",
          ],
        ],
        [
          "How do I run a dataset from Hub, and how do I share results?",
          [
            "ageval registry list shows datasets you can see. Then ageval run <org>/<name>@<version>. You can also run a local dataset root. Default profiles use environment: docker, so a working Docker engine is required.",
            "Share or reuse datasets, plugins, and Agent configurations on ageval Hub, and upload evaluation results. Others should be able to run what you shared, not only read a score table. Locally, ageval view opens a run under Jobs → Tasks.",
          ],
        ],
        [
          "What files belong in a dataset?",
          [
            "The unit of delivery is a dataset. Put ageval.yaml at the root. Each task lives in tasks/<id>/ with task.yaml, the loop in run.py, scoring in evaluator.py, and gold. Environment and Agent go in profiles.yaml; do not bake one runtime into the dataset.",
            "The task keeps the loop, roles, and local tools. ageval owns lock, opening the environment, binding the score, and cleanup. The SDK is optional: it does not decide PASS and does not hold host credentials.",
          ],
        ],
        [
          "How do I plug in my own environment or Agent?",
          [
            "Write a plugin for the running base. Do not fork ageval. The plugin declares whether it adds an environment or an agent runtime; after install, switch it in config. ACP is the default path; dsh, nooa, and miniswe are the same kind of plugin.",
            "If the plugin's capabilities or credentials do not match, ageval lock fails and the run does not start.",
          ],
        ],
        [
          "If I switch among host, Docker, and a cloud sandbox, do I rewrite the dataset? Can the Agent see gold?",
          [
            "No rewrite. Change the environment in profiles.yaml: host, Docker, or E2B / SSH / Daytona. The same task runs in each.",
            "Keep gold in tasks/<id>/evaluation/. It is not mounted while the Agent runs. It uploads into the environment at evaluate.",
          ],
        ],
      ] as const,
    },
    footer: {
      body: "ageval — agent eval. Maintained by ZJU-REAL. GitHub: ZJU-REAL/ageval.",
      mark: "ZJU-REAL · ageval",
    },
  },
} as const;

export type LandingCopy = (typeof landingCopy)[SiteLocale];
